import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowTrendingUpIcon,
  CheckIcon,
  GlobeAltIcon,
  LightBulbIcon,
  MapPinIcon,
  MegaphoneIcon,
  ShieldCheckIcon,
  UserGroupIcon,
  WalletIcon,
} from "@heroicons/react/24/outline";
import { Navigation } from "@/components/layout";
import { LandingFooter } from "@/components/landing";

export const metadata: Metadata = {
  title: "Partner Program - vayada",
  description:
    "Refer independent hotels, villas and boutique stays to vayada and earn recurring revenue share for up to three years.",
};

const steps = [
  {
    n: "1",
    title: "Refer a property",
    body: "Introduce us to independent hotels, villas, serviced apartments or boutique stays in your network.",
  },
  {
    n: "2",
    title: "We onboard them",
    body: "Our team helps the property set up vayada, connect their booking flow and start using the platform.",
  },
  {
    n: "3",
    title: "You earn for 3 years",
    body: "Receive revenue share for every referred customer that becomes active and pays through vayada.",
  },
];

const revenueShare = [
  {
    year: "Year 1",
    value: "20%",
    body: "Earn 20% of the revenue generated by every referred customer in the first year.",
  },
  {
    year: "Year 2",
    value: "15%",
    body: "Continue earning 15% in the second year as the customer keeps growing with vayada.",
  },
  {
    year: "Year 3",
    value: "10%",
    body: "Receive 10% in the third year for long-term value created through your introduction.",
  },
];

const audiences = [
  {
    icon: MegaphoneIcon,
    title: "Hospitality creators",
    body: "Creators with hotel, villa, travel or destination audiences who can introduce properties to modern direct booking tools.",
  },
  {
    icon: GlobeAltIcon,
    title: "Website & marketing agencies",
    body: "Agencies building websites, branding, SEO, paid ads or social media for hospitality clients.",
  },
  {
    icon: MapPinIcon,
    title: "Local connectors",
    body: "People with strong relationships in tourism markets, especially in high-growth destinations.",
  },
  {
    icon: LightBulbIcon,
    title: "Consultants & hospitality experts",
    body: "Advisors helping properties improve operations, distribution, revenue or guest experience.",
  },
];

const outcomes = [
  {
    icon: ArrowTrendingUpIcon,
    title: "More direct bookings",
    body: "Properties get a modern booking engine designed to convert direct demand.",
  },
  {
    icon: ShieldCheckIcon,
    title: "Lower OTA dependency",
    body: "Hotels and villas can reduce reliance on Booking.com, Airbnb and other third-party platforms.",
  },
  {
    icon: WalletIcon,
    title: "More revenue per stay",
    body: "Properties can upsell services, experiences and transportation during the booking journey.",
  },
  {
    icon: UserGroupIcon,
    title: "Guest ownership",
    body: "Every direct booking helps properties capture guest data and build stronger relationships.",
  },
];

const partnerWins = [
  "Recurring revenue for up to 3 years",
  "Strong product for a real market need",
  "No technical setup required",
  "Simple introduction process",
  "We handle onboarding and support",
  "Upside as referred properties grow",
];

const referralTypes = [
  "Boutique hotels",
  "Villas",
  "Surf camps",
  "Guesthouses",
  "Serviced apartments",
  "Small hotel groups",
  "Destination stays",
  "Eco resorts",
  "Airbnb-style properties with their own brand",
  "Property Management Agencies",
];

const example = [
  { year: "Year 1", value: "20% = $60/mo" },
  { year: "Year 2", value: "15% = $45/mo" },
  { year: "Year 3", value: "10% = $30/mo" },
];

function Eyebrow({ children }: { children: React.ReactNode }) {
  return <p className="text-xs uppercase tracking-[0.2em] text-primary-500">{children}</p>;
}

function SectionHeading({
  eyebrow,
  title,
  centered = true,
}: {
  eyebrow: string;
  title: string;
  centered?: boolean;
}) {
  return (
    <div className={centered ? "mx-auto max-w-3xl text-center" : "max-w-3xl"}>
      <Eyebrow>{eyebrow}</Eyebrow>
      <h2 className="mt-4 font-display text-3xl font-semibold leading-tight text-ink md:text-5xl">
        {title}
      </h2>
    </div>
  );
}

function IconCard({
  icon: Icon,
  title,
  body,
}: {
  icon: typeof MegaphoneIcon;
  title: string;
  body: string;
}) {
  return (
    <div className="rounded-3xl border border-border bg-[#f7f8fc]/70 p-8 shadow-soft">
      <div className="grid h-11 w-11 place-items-center rounded-xl bg-primary-50 text-primary-500">
        <Icon className="h-5 w-5" />
      </div>
      <h3 className="mt-5 font-display text-lg font-semibold text-ink">{title}</h3>
      <p className="mt-3 text-sm leading-relaxed text-gray-500">{body}</p>
    </div>
  );
}

export default function PartnerProgramPage() {
  return (
    <main className="min-h-screen bg-white text-ink">
      <Navigation />

      <section className="relative overflow-hidden pt-32 pb-16 md:pt-40 md:pb-24">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(47,82,245,0.14),transparent_42%),linear-gradient(180deg,#f7f8fc_0%,#fff_70%)]" />
        <div className="relative mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-xs uppercase tracking-[0.2em] text-primary-500 transition-colors hover:text-primary-600"
          >
            <ArrowLeftIcon className="h-3.5 w-3.5" />
            Partner Program
          </Link>
          <h1 className="mt-5 font-display text-4xl font-semibold leading-[1.05] text-ink md:text-6xl">
            Build recurring revenue from your{" "}
            <span className="text-primary-500">hospitality network</span>
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-gray-500">
            Refer independent hotels, villas and boutique stays to vayada and earn long-term revenue
            share while helping properties reduce OTA dependency, grow direct bookings and modernize
            their operations.
          </p>
          <p className="mt-6 font-display text-lg text-ink">
            <span className="font-semibold text-primary-500">20%</span> in year one ·{" "}
            <span className="font-semibold text-primary-500">15%</span> in year two
            <br />· <span className="font-semibold text-primary-500">10%</span> in year three
          </p>
          <div className="mt-10 flex justify-center">
            <a
              href="#apply"
              className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-primary-500 px-7 text-base font-medium text-white shadow-glow transition-all hover:bg-primary-600"
            >
              Apply as partner
              <ArrowRightIcon className="h-4 w-4" />
            </a>
          </div>
        </div>
      </section>

      <section className="relative py-20 md:py-28">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <Eyebrow>Why partner</Eyebrow>
          <h2 className="mt-4 font-display text-3xl font-semibold leading-tight text-ink md:text-5xl">
            Why partner with vayada?
          </h2>
          <div className="mt-8 space-y-5 text-lg leading-relaxed text-gray-500">
            <p>
              Independent properties are actively looking for better ways to manage bookings, reduce
              OTA dependency and grow direct revenue. But many still rely on outdated tools, manual
              workflows or expensive third-party platforms.
            </p>
            <p>
              vayada gives them a modern booking engine, PMS and channel manager in one system, plus
              referral tracking and upselling for more direct revenue.
            </p>
            <p>
              As a partner, you bring trusted introductions. We handle product, onboarding and
              support.
            </p>
          </div>
        </div>
      </section>

      <section className="relative bg-[#f7f8fc]/60 py-20 md:py-28">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <SectionHeading eyebrow="How it works" title="Three simple steps" />
          <div className="mt-14 grid gap-6 md:grid-cols-3">
            {steps.map((step) => (
              <div
                key={step.n}
                className="rounded-3xl border border-border bg-white p-8 shadow-soft"
              >
                <span className="grid h-10 w-10 place-items-center rounded-xl bg-primary-500 font-display font-semibold text-white">
                  {step.n}
                </span>
                <h3 className="mt-5 font-display text-xl font-semibold text-ink">{step.title}</h3>
                <p className="mt-3 text-sm leading-relaxed text-gray-500">{step.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="relative py-20 md:py-28">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <SectionHeading eyebrow="Your revenue share" title="Earn for three years" />
          <div className="mt-10 grid gap-4 md:mt-14 md:grid-cols-3 md:gap-6">
            {revenueShare.map((item) => (
              <div
                key={item.year}
                className="rounded-3xl border border-border-strong bg-white p-5 text-center shadow-soft md:p-8"
              >
                <div className="text-xs uppercase tracking-[0.2em] text-gray-500">{item.year}</div>
                <div className="mt-2 font-display text-4xl font-semibold text-primary-500 md:mt-3 md:text-6xl">
                  {item.value}
                </div>
                <p className="mt-3 text-sm leading-relaxed text-gray-500 md:mt-4">{item.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="relative py-20 md:py-28">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <SectionHeading eyebrow="Who it's for" title="Who the program is for" />
          <div className="mx-auto mt-14 grid max-w-4xl gap-6 md:grid-cols-2">
            {audiences.map((item) => (
              <IconCard key={item.title} {...item} />
            ))}
          </div>
        </div>
      </section>

      <section className="relative bg-[#f7f8fc]/60 py-20 md:py-28">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <SectionHeading eyebrow="Customer impact" title="What you help properties unlock" />
          <div className="mx-auto mt-14 grid max-w-4xl gap-6 md:grid-cols-2">
            {outcomes.map((item) => (
              <IconCard key={item.title} {...item} />
            ))}
          </div>
        </div>
      </section>

      <section className="relative py-20 md:py-28">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="rounded-3xl border border-border-strong bg-primary-50 p-8 shadow-soft md:p-14">
            <SectionHeading eyebrow="Why partners win" title="Built to be a real revenue stream" />
            <ul className="mt-10 grid gap-4 md:grid-cols-2">
              {partnerWins.map((item) => (
                <li
                  key={item}
                  className="flex items-start gap-3 rounded-2xl border border-border bg-white p-5"
                >
                  <span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-primary-50 text-primary-500">
                    <CheckIcon className="h-3 w-3" strokeWidth={3} />
                  </span>
                  <span className="text-sm leading-relaxed text-ink sm:text-base">{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      <section className="relative py-20 md:py-28">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="rounded-3xl border border-border bg-[#f7f8fc]/70 p-8 shadow-soft md:p-14">
            <Eyebrow>Example</Eyebrow>
            <h2 className="mt-4 font-display text-3xl font-semibold text-ink md:text-4xl">
              A real-world calculation
            </h2>
            <p className="mt-5 text-base leading-relaxed text-gray-500">
              A hotel joins vayada through your introduction and pays{" "}
              <span className="font-semibold text-ink">$300/month</span>.
            </p>
            <div className="mt-8 grid gap-4 md:grid-cols-3">
              {example.map((item) => (
                <div
                  key={item.year}
                  className="rounded-2xl border border-border-strong bg-white p-5 text-center"
                >
                  <div className="text-xs uppercase tracking-[0.2em] text-gray-500">
                    {item.year}
                  </div>
                  <div className="mt-2 font-display text-xl font-semibold text-primary-500">
                    {item.value}
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-6 rounded-2xl border border-primary-500/30 bg-primary-50 p-5 text-center">
              <div className="text-xs uppercase tracking-[0.2em] text-primary-500">
                Total over 3 years
              </div>
              <div className="mt-2 font-display text-3xl font-semibold text-primary-500">
                up to $1,620
              </div>
            </div>
            <p className="mt-8 text-sm leading-relaxed text-gray-500">
              The more properties you refer, the more recurring partner revenue you build.
            </p>
          </div>
        </div>
      </section>

      <section className="relative py-20 md:py-28">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
          <SectionHeading
            eyebrow="Referral fit"
            title="What makes a good referral?"
            centered={false}
          />
          <p className="mt-5 max-w-2xl text-lg leading-relaxed text-gray-500">
            A strong fit is usually an independent property that wants to grow direct bookings and
            improve operations.
          </p>
          <div className="mt-10 flex flex-wrap gap-3">
            {referralTypes.map((type) => (
              <span
                key={type}
                className="inline-flex items-center gap-2 rounded-full border border-border-strong bg-white px-4 py-2 text-sm text-ink shadow-soft"
              >
                <CheckIcon className="h-3.5 w-3.5 shrink-0 text-primary-500" />
                {type}
              </span>
            ))}
          </div>
        </div>
      </section>

      <section id="apply" className="relative py-14 md:py-32">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="relative overflow-hidden rounded-3xl border border-border-strong bg-gradient-to-br from-primary-50 via-white to-primary-50 p-8 text-center shadow-soft md:p-20">
            <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(47,82,245,0.12),transparent_46%)]" />
            <div className="relative mx-auto max-w-2xl">
              <h2 className="font-display text-4xl font-semibold leading-tight text-ink md:text-6xl">
                Ready to become a <span className="text-primary-500">vayada</span> partner?
              </h2>
              <p className="mt-5 text-lg leading-relaxed text-gray-500">
                Introduce properties in your network to modern direct booking infrastructure and
                earn revenue share for up to three years.
              </p>
              <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
                <a
                  href="mailto:t.schreyer@vayada.com?subject=Partner%20Program%20application"
                  className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-primary-500 px-7 text-sm font-medium text-white shadow-glow transition-all hover:bg-primary-600"
                >
                  Apply as partner
                  <ArrowRightIcon className="h-4 w-4" />
                </a>
                <a
                  href="mailto:t.schreyer@vayada.com?subject=Partner%20Program%20question"
                  className="inline-flex h-12 items-center justify-center rounded-full border border-border-strong bg-white px-7 text-sm text-ink transition-colors hover:bg-surface-elevated"
                >
                  Talk to us first
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      <LandingFooter />
    </main>
  );
}
