ALTER TABLE booking_hotels
  ADD COLUMN IF NOT EXISTS paypal_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS paypal_email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS paypal_payment_window_hours INTEGER NOT NULL DEFAULT 24;
