import { createHash } from "node:crypto";
import pg from "pg";
import {
  seedChannexAssignmentFixture,
  clearChannexAssignmentFixture,
} from "./channexAssignmentTestFixture.js";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { runChannexBookingJobs } from "./channexBookings.js";

const URL = process.env["TEST_DATABASE_URL"],
  P = "11890000-0000-4000-8000-000000000001",
  C = "11890000-0000-4000-8000-000000000002",
  T = "11890000-0000-4000-8000-000000000003",
  R = "11890000-0000-4000-8000-000000000004",
  EXTERNAL = "chx-vay-1189";
if (URL && !/(^|[_-])(test|verify)([_-]|$)/i.test(new globalThis.URL(URL).pathname))
  throw new Error("Refusing non-test database");

// prettier-ignore
describe.skipIf(!URL)("Channex booking worker (PostgreSQL)",()=>{
  const db=new pg.Pool({connectionString:URL??"postgresql://disabled",max:4});let sequence=0,feed:Record<string,unknown>[]=[],owns=true,loseAck:string|null=null;const calls:string[]=[],acked=new Set<string>();
  const fetcher:typeof fetch=async(input,init)=>{const url=String(input),method=init?.method??"GET";calls.push(`${method} ${url}`);if(method==="GET")return Response.json({data:feed});const revisionId=url.split("/").at(-2)!,durable=await db.query("SELECT 1 FROM platform.jobs WHERE job_metadata->'handledRevisions' ? $1 LIMIT 1",[revisionId]);expect(durable.rowCount).toBe(1);const repeated=acked.has(revisionId);acked.add(revisionId);if(loseAck===revisionId){loseAck=null;throw new Error("ACK response lost")}return new Response(null,{status:repeated?404:204});};
  beforeAll(async()=>{await cleanup();await db.query("INSERT INTO hotel_catalog.properties(id,public_id,display_name) VALUES($1,'vay-1189','Channex worker')",[P]);await db.query("INSERT INTO pms.channel_binding_claims(property_id,provider,external_property_id,claim_state,claim_source) VALUES($1,'channex',$2,'active','repair')",[P,EXTERNAL]);await db.query("INSERT INTO pms.channel_connections(id,property_id,provider,connection_status,external_property_id) VALUES($2,$1,'channex','connected',$3)",[P,C,EXTERNAL]);await seedChannexAssignmentFixture(db,P);await db.query("INSERT INTO pms.room_types(id,property_id,name,currency,base_rate_amount) VALUES($1,$2,'Channel room next','EUR',100)",[T,P]);await db.query("INSERT INTO pms.rate_plans(id,property_id,room_type_id,code,name,currency) VALUES($1,$2,$3,'channel-next','Channel rate next','EUR')",[R,P,T]);await db.query("INSERT INTO pms.channel_room_type_mappings(property_id,connection_id,room_type_id,external_room_type_id) VALUES($1,$2,$3,'provider-room-next')",[P,C,T]);await db.query("INSERT INTO pms.channel_rate_plan_mappings(property_id,connection_id,room_type_id,rate_plan_id,external_room_type_id,external_rate_plan_id) VALUES($1,$2,$3,$4,'provider-room-next','provider-rate-next')",[P,C,T,R]);await db.query("WITH configured AS (SELECT set_config('session_replication_role','replica',true)) INSERT INTO pms.operating_calendar_room_bindings(property_id,calendar_revision,room_type_id,source_room_facts_revision,source_room_units_revision,physical_capacity_count,starting_sellable_limit_count) SELECT $1,1,$2,1,1,100,100 FROM configured",[P,T]);await db.query("INSERT INTO pms.inventory_days(property_id,room_type_id,stay_date,total_count,available_count,calendar_revision,effective_sellable_limit_count,inventory_revision,generated_sellable_limit_count,generated_source_revision,channel_source_revision,manual_source_revision,block_source_revision,booking_source_revision) SELECT $1,$2,day,100,100,1,100,1,100,1,0,0,0,0 FROM generate_series('2026-09-01'::date,'2026-10-31'::date,'1 day') day",[P,T]);});
  afterAll(async()=>{await cleanup();await db.end();});

  it("pulls, attributes, replays, retries atomically, dead-letters, and acknowledges only durable revisions",async()=>{
    feed=[revision("rev-booking","booking-1","BookingCom",2),revision(8,"booking-1","BookingCom",2)];const first=await job("booking-1","unknown",true,feed[0]!);expect(await run()).toEqual({succeeded:1,retryScheduled:0,deadLettered:0});
    const saved=await db.query(`SELECT booking_channel,(SELECT count(*)::int FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id) mappings,
      (SELECT bool_or(assignment_payload->'channexStay' ? 'days') FROM pms.operational_booking_assignments WHERE guest_booking_id=booking.id) AS "pmsPrices",
      (SELECT mapping_metadata->>'providerSource' FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id LIMIT 1) source
      FROM booking.guest_bookings booking WHERE source_booking_id=$1`,[`channex:${P}:booking-1`]);expect(saved.rows[0]).toEqual({booking_channel:"booking_com",mappings:2,pmsPrices:false,source:"BookingCom"});
    expect((await revenue("booking-1")).rows[0]).toMatchObject({lines:4,occupied:4,amount:"240.0000",ota:true,exact:true});
    feed=[];await db.query("UPDATE platform.jobs SET status='pending',finished_at=NULL,run_after=now() WHERE id=$1",[first]);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT count(*)::int count FROM booking.guest_bookings WHERE source_booking_id=$1",[`channex:${P}:booking-1`])).rows[0].count).toBe(1);expect((await revenue("booking-1")).rows[0].lines).toBe(4);
    const partial=revision("partial-contact","booking-1","Expedia");partial.attributes.inserted_at="2026-08-20T12:00:00.123400Z";partial.attributes.amount="120.00";partial.attributes.rooms[0]!.days={"2026-09-01":"70.00","2026-09-02":"50.00"};Object.assign(partial.attributes,{customer:{name:"Partial"}});await job("booking-1","partial-contact",false,partial);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT first_name,email,phone FROM booking.booking_guests guest JOIN booking.guest_bookings booking ON booking.id=guest.guest_booking_id WHERE booking.source_booking_id=$1",[`channex:${P}:booking-1`])).rows[0]).toEqual({first_name:"Partial",email:"guest@example.test",phone:"+100"});expect((await revenue("booking-1")).rows[0]).toMatchObject({lines:8,occupied:2,amount:"120.0000",corrections:2,adjustments:2});
    const changed=revision(9,"booking-1","Expedia",0);changed.attributes.status="cancelled";changed.attributes.inserted_at="2026-08-20T12:00:00.123456Z";changed.attributes.customer={name:"Grace",surname:"Changed",mail:"changed@example.test",phone:"+123"};await job("booking-1","9",false,changed);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT lifecycle_status,booking_channel,room_count,(SELECT count(*)::int FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id AND sync_status='active') active,(SELECT first_name FROM booking.booking_guests WHERE guest_booking_id=booking.id AND guest_role='booker') guest,(SELECT email FROM booking.booking_guests WHERE guest_booking_id=booking.id AND guest_role='booker') email,(SELECT mapping_metadata->>'providerSource' FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id LIMIT 1) original,(SELECT mapping_metadata->>'latestProviderSource' FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id LIMIT 1) latest FROM booking.guest_bookings booking WHERE source_booking_id=$1",[`channex:${P}:booking-1`])).rows[0]).toEqual({lifecycle_status:"canceled",booking_channel:"booking_com",room_count:1,active:1,guest:"Grace",email:"changed@example.test",original:"BookingCom",latest:"Expedia"});expect((await revenue("booking-1")).rows[0]).toMatchObject({lines:10,occupied:0,amount:"0.0000",adjustments:4,retained:0,refunds:0});
    const older=revision(7,"booking-1","Airbnb");older.attributes.inserted_at="2026-08-20T12:00:00.123123Z";feed=[older];loseAck="7";const stale=await job("booking-1","7",true,older);expect((await run()).retryScheduled).toBe(1);feed=[];await db.query("UPDATE platform.jobs SET run_after=now() WHERE id=$1",[stale]);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT booking.booking_channel,booking.lifecycle_status,guest.first_name,(SELECT external_revision_id FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id AND sync_status='active' LIMIT 1) revision,job.job_metadata->'handledRevisions'->'7'->>'outcome' outcome,length(job.job_metadata->'handledRevisions'->'7'->>'fingerprint') fingerprint FROM booking.guest_bookings booking JOIN booking.booking_guests guest ON guest.guest_booking_id=booking.id AND guest.guest_role='booker' JOIN platform.jobs job ON job.id=$1::uuid WHERE booking.source_booking_id=$2",[stale,`channex:${P}:booking-1`])).rows[0]).toEqual({booking_channel:"booking_com",lifecycle_status:"canceled",first_name:"Grace",revision:"9",outcome:"stale",fingerprint:64});
    const providerShaped=revision("rev-other","booking-2","Hostelworld");providerShaped.attributes.inserted_at="2019-04-23T10:03:29.335485";Reflect.deleteProperty(providerShaped.attributes.rooms[0]!,"days");await job("booking-2","rev-other",false,providerShaped);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT mapping_metadata->>'providerInsertedAt' inserted FROM pms.channel_booking_mappings WHERE connection_id=$1 AND external_booking_id='booking-2'",[C])).rows[0].inserted).toBe("2019-04-23T10:03:29.335485Z");expect((await revenue("booking-2")).rows[0]).toMatchObject({lines:2,occupied:2,amount:null,ota:true,exact:false});
    await job("booking-3","rev-unknown",false,revision("rev-unknown","booking-3",null));expect((await run()).succeeded).toBe(1);const expanded=revision("rev-unknown-expanded","booking-3","Expedia",2);await job("booking-3","rev-unknown-expanded",false,expanded);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT count(*)::int mappings,count(*) FILTER(WHERE mapping_metadata->>'providerSource' IS NOT NULL)::int sources FROM pms.channel_booking_mappings WHERE connection_id=$1 AND external_booking_id='booking-3'",[C])).rows[0]).toEqual({mappings:2,sources:0});
    for(const [id,source] of [["4","Airbnb"],["5","Expedia.com"],["6","Agoda"]] as const){await job(`booking-${id}`,`rev-${id}`,false,revision(`rev-${id}`,`booking-${id}`,source));expect((await run()).succeeded).toBe(1)}expect((await db.query("SELECT source_booking_id,booking_channel FROM booking.guest_bookings WHERE property_id=$1 ORDER BY source_booking_id",[P])).rows.map(row=>row.booking_channel)).toEqual(["booking_com","other_ota","unknown","airbnb","expedia","agoda"]);
    for(const [hint,key] of [[41,"revision"],["42","revision_number"]] as const){const semantic=revision(`semantic-${hint}`,`booking-hint-${hint}`,"Agoda");Object.assign(semantic.attributes,{[key]:hint});if(hint===41){Object.assign(semantic.attributes,{occupancy:{adults:1,children:0}});Reflect.deleteProperty(semantic.attributes.rooms[0]!,"occupancy");loseAck=String(semantic.id)}feed=[semantic];const semanticJob=await job(`booking-hint-${hint}`,String(hint),true,semantic);expect((await run())[hint===41?"retryScheduled":"succeeded"]).toBe(1);if(hint===41){feed=[];await db.query("UPDATE platform.jobs SET run_after=now() WHERE id=$1",[semanticJob]);expect((await run()).succeeded).toBe(1)}}
    const feedFirst=revision("alias-feed-first","booking-alias-feed","Agoda");Object.assign(feedFirst.attributes,{revision:51});await job("booking-alias-feed","alias-feed-first",false,feedFirst);expect((await run()).succeeded).toBe(1);feed=[];await job("booking-alias-feed","51",true,feedFirst);expect((await run()).succeeded).toBe(1);const webhookFirst=revision("alias-webhook-first","booking-alias-webhook","Agoda");Object.assign(webhookFirst.attributes,{revision_number:"52"});feed=[webhookFirst];await job("booking-alias-webhook","52",true,webhookFirst);expect((await run()).succeeded).toBe(1);feed=[];await job("booking-alias-webhook","alias-webhook-first",false,webhookFirst);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT count(DISTINCT alias)::int count FROM platform.jobs evidence,jsonb_each(evidence.job_metadata->'handledRevisions') handled,jsonb_array_elements_text(handled.value->'aliases') alias WHERE evidence.payload->>'propertyId'=$1 AND alias IN('51','alias-feed-first','52','alias-webhook-first')",[P])).rows[0].count).toBe(4);expect((await revenue("booking-alias-feed")).rows[0].lines).toBe(2);expect((await revenue("booking-alias-webhook")).rows[0].lines).toBe(2);
    const compatible=revision("v2-compatible","booking-v2","Agoda"),compatibleJob=await job("booking-v2","v2-compatible",false,compatible);expect((await run()).succeeded).toBe(1);await db.query(`UPDATE platform.jobs SET status='pending',finished_at=NULL,run_after=now(),job_metadata=jsonb_set(jsonb_set(job_metadata,'{handledRevisions,v2-compatible,fingerprint}',$2::jsonb),'{handledRevisions,v2-compatible,fingerprintVersion}','2') WHERE id=$1`,[compatibleJob,JSON.stringify(v2Fingerprint(compatible))]);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT job_metadata->'handledRevisions'->'v2-compatible'->>'fingerprintVersion' version FROM platform.jobs WHERE id=$1",[compatibleJob])).rows[0].version).toBe("3");
    const exact=revision("exact-before-missing","booking-exact-missing","Agoda");await job("booking-exact-missing","exact-before-missing",false,exact);expect((await run()).succeeded).toBe(1);const noPrices=revision("exact-now-missing","booking-exact-missing","Agoda");noPrices.attributes.status="modified";noPrices.attributes.rooms.forEach(room=>Reflect.deleteProperty(room,"days"));const noPricesJob=await job("booking-exact-missing","exact-now-missing",false,noPrices);expect((await run()).succeeded).toBe(1);expect((await revenue("booking-exact-missing")).rows[0]).toMatchObject({lines:6,occupied:2,amount:"0.0000",adjustments:4,exact:false});expect((await db.query(`SELECT bool_and(evidence_quality='missing') missing FROM (SELECT DISTINCT ON(stay_date,line_position) evidence_quality FROM booking.nightly_revenue_evidence evidence JOIN booking.guest_bookings booking ON booking.id=evidence.guest_booking_id WHERE booking.source_booking_id=$1 AND economic_event<>'retained_charge' ORDER BY stay_date,line_position,source_revision DESC,evidence.created_at DESC,evidence.id DESC) tips`,[`channex:${P}:booking-exact-missing`])).rows[0].missing).toBe(true);await db.query("UPDATE platform.jobs SET status='pending',finished_at=NULL,run_after=now() WHERE id=$1",[noPricesJob]);expect((await run()).succeeded).toBe(1);expect((await revenue("booking-exact-missing")).rows[0].lines).toBe(6);
    await job("booking-room-move","room-move-create",false,revision("room-move-create","booking-room-move","Agoda"));expect((await run()).succeeded).toBe(1);const moved=revision("room-move-change","booking-room-move","Agoda");moved.attributes.status="modified";moved.attributes.amount="160.00";Object.assign(moved.attributes.rooms[0]!,{room_type_id:"provider-room-next",rate_plan_id:"provider-rate-next",days:{"2026-09-01":"80.00","2026-09-02":"80.00"}});await job("booking-room-move","room-move-change",false,moved);expect((await run()).succeeded).toBe(1);expect((await revenue("booking-room-move")).rows[0]).toMatchObject({lines:6,occupied:2,amount:"160.0000",adjustments:4});expect((await db.query(`SELECT bool_and(room_type_id=$2::uuid) moved FROM (SELECT DISTINCT ON(stay_date,line_position) room_type_id FROM booking.nightly_revenue_evidence evidence JOIN booking.guest_bookings booking ON booking.id=evidence.guest_booking_id WHERE booking.source_booking_id=$1 AND economic_event<>'retained_charge' ORDER BY stay_date,line_position,source_revision DESC,evidence.created_at DESC,evidence.id DESC) tips`,[`channex:${P}:booking-room-move`,T])).rows[0].moved).toBe(true);
    await job("booking-date-move","date-move-create",false,revision("date-move-create","booking-date-move","Agoda"));expect((await run()).succeeded).toBe(1);const dateMoved=revision("date-move-change","booking-date-move","Agoda");dateMoved.attributes.status="modified";dateMoved.attributes.arrival_date="2026-09-02";dateMoved.attributes.departure_date="2026-09-04";dateMoved.attributes.inserted_at="2026-10-06T22:30:00.000Z";Object.assign(dateMoved.attributes.rooms[0]!,{days:{"2026-09-02":"60.00","2026-09-03":"60.00"}});await job("booking-date-move","date-move-change",false,dateMoved);expect((await run()).succeeded).toBe(1);expect((await revenue("booking-date-move")).rows[0]).toMatchObject({lines:4,occupied:2,amount:"120.0000",adjustments:2});expect((await db.query("SELECT array_agg(DISTINCT recognized_on::text ORDER BY recognized_on::text) dates FROM booking.nightly_revenue_evidence evidence JOIN booking.guest_bookings booking ON booking.id=evidence.guest_booking_id WHERE booking.source_booking_id=$1 AND economic_event='occupancy_adjustment'",[`channex:${P}:booking-date-move`])).rows[0].dates).toEqual(["2026-10-07"]);
    await job("booking-retained","retained-create",false,revision("retained-create","booking-retained","BookingCom"));expect((await run()).succeeded).toBe(1);const retained=revision("retained-cancel","booking-retained","BookingCom",0);retained.attributes.status="cancelled";retained.attributes.inserted_at="2026-10-02T22:30:00.000Z";Object.assign(retained.attributes,{services:[{type:"Cancellation Fee",name:"Cancellation Fee",total_price:"38.25"},{type:"Cancellation Fee",name:"Cancellation Fee",total_price:"38.25"}]});await job("booking-retained","retained-cancel",false,retained);expect((await run()).succeeded).toBe(1);expect((await revenue("booking-retained")).rows[0]).toMatchObject({lines:5,occupied:0,amount:"76.5000",adjustments:2,retained:1,refunds:0});expect((await db.query("SELECT array_agg(DISTINCT recognized_on::text ORDER BY recognized_on::text) dates FROM booking.nightly_revenue_evidence evidence JOIN booking.guest_bookings booking ON booking.id=evidence.guest_booking_id WHERE booking.source_booking_id=$1 AND lifecycle_state='canceled'",[`channex:${P}:booking-retained`])).rows[0].dates).toEqual(["2026-10-03"]);const retainedCorrection=revision("retained-correction","booking-retained","BookingCom",0);retainedCorrection.attributes.status="cancelled";retainedCorrection.attributes.inserted_at="2026-10-03T22:30:00.000Z";Object.assign(retainedCorrection.attributes,{services:[{type:"Cancellation Fee",name:"Cancellation Fee",total_price:"50.00"}]});await job("booking-retained","retained-correction",false,retainedCorrection);expect((await run()).succeeded).toBe(1);expect((await revenue("booking-retained")).rows[0]).toMatchObject({lines:6,occupied:0,amount:"50.0000",corrections:1,retained:1});const retainedRemoved=revision("retained-removed","booking-retained","BookingCom",0);retainedRemoved.attributes.status="cancelled";retainedRemoved.attributes.inserted_at="2026-10-04T22:30:00.000Z";await job("booking-retained","retained-removed",false,retainedRemoved);expect((await run()).succeeded).toBe(1);expect((await revenue("booking-retained")).rows[0]).toMatchObject({lines:7,occupied:0,amount:"0.0000",corrections:2,retained:1});expect((await db.query("SELECT array_agg(recognized_on::text ORDER BY source_revision) dates FROM booking.nightly_revenue_evidence evidence JOIN booking.guest_bookings booking ON booking.id=evidence.guest_booking_id WHERE booking.source_booking_id=$1 AND economic_event='correction'",[`channex:${P}:booking-retained`])).rows[0].dates).toEqual(["2026-10-04","2026-10-05"]);
    await job("booking-ambiguous-fee","ambiguous-create",false,revision("ambiguous-create","booking-ambiguous-fee","BookingCom",2));expect((await run()).succeeded).toBe(1);const ambiguous=revision("ambiguous-cancel","booking-ambiguous-fee","BookingCom",0);ambiguous.attributes.status="cancelled";Object.assign(ambiguous.attributes,{services:[{type:"Cancellation Fee",name:"Cancellation Fee",total_price:"50.00"}]});await job("booking-ambiguous-fee","ambiguous-cancel",false,ambiguous,1);expect((await run()).deadLettered).toBe(1);expect((await db.query("SELECT lifecycle_status FROM booking.guest_bookings WHERE source_booking_id=$1",[`channex:${P}:booking-ambiguous-fee`])).rows[0].lifecycle_status).toBe("confirmed");expect((await revenue("booking-ambiguous-fee")).rows[0]).toMatchObject({lines:4,occupied:4,amount:"240.0000",retained:0});
    await db.query("INSERT INTO pms.inventory_days(property_id,room_type_id,stay_date,total_count,available_count,calendar_revision,effective_sellable_limit_count,inventory_revision,generated_sellable_limit_count,generated_source_revision,channel_source_revision,manual_source_revision,block_source_revision,booking_source_revision) SELECT $1,room_type_id,day,100,100,1,100,1,100,1,0,0,0,0 FROM pms.channel_room_type_mappings CROSS JOIN generate_series('2026-10-01'::date,'2026-10-31'::date,'1 day') day WHERE property_id=$1 AND external_room_type_id='provider-room'",[P]);const large=revision("large-revision","booking-large","Agoda",20);Object.assign(large.attributes,{arrival_date:"2026-09-10",departure_date:"2026-10-31",amount:"61200.00"});const largeDays=Object.fromEntries(Array.from({length:51},(_,index)=>{const date=new Date(Date.UTC(2026,8,10+index));return[date.toISOString().slice(0,10),"60.00"]}));large.attributes.rooms.forEach(room=>Object.assign(room,{days:largeDays}));await job("booking-large","large-revision",false,large);expect(await run()).toEqual({succeeded:1,retryScheduled:0,deadLettered:0});expect((await db.query("SELECT count(*)::int lines,count(DISTINCT source_revision)::int revisions FROM booking.nightly_revenue_evidence evidence JOIN booking.guest_bookings booking ON booking.id=evidence.guest_booking_id WHERE booking.source_booking_id=$1",[`channex:${P}:booking-large`])).rows[0]).toEqual({lines:1020,revisions:2});

    owns=false;const frozen=await job("booking-frozen","rev-frozen",false,revision("rev-frozen","booking-frozen","Agoda"),1);expect((await run()).deadLettered).toBe(1);owns=true;expect((await db.query("SELECT status,(SELECT count(*)::int FROM platform.dead_letter_events WHERE job_id=job.id) dead FROM platform.jobs job WHERE id=$1",[frozen])).rows[0]).toEqual({status:"dead_lettered",dead:1});
    await db.query("INSERT INTO platform.jobs(job_key,queue_name,job_type,tenant_scope,resource_product,resource_type,resource_id,payload) VALUES($1,'pms.channex.webhooks','channex.ingest-booking','external','pms','channel_booking','malformed','{}')",[`vay-1189:${++sequence}`]);expect((await run()).deadLettered).toBe(1);
    const missing=revision("missing-rooms","booking-missing","Agoda");Reflect.deleteProperty(missing.attributes,"rooms");await job("booking-missing","missing-rooms",false,missing,1);expect((await run()).deadLettered).toBe(1);const bad=revision("bad-occupancy","booking-bad","Agoda");bad.attributes.rooms[0]!.occupancy.adults=-1;await job("booking-bad","bad-occupancy",false,bad,1);expect((await run()).deadLettered).toBe(1);const empty=revision("multi-empty","booking-multi-empty","Agoda",2);Object.assign(empty.attributes,{occupancy:{adults:2,children:0}});empty.attributes.rooms.forEach(room=>Object.assign(room,{occupancy:{}}));await job("booking-multi-empty","multi-empty",false,empty,1);expect((await run()).deadLettered).toBe(1);const partialRoom=revision("multi-partial","booking-multi-partial","Agoda",2);Object.assign(partialRoom.attributes,{occupancy:{adults:2,children:0}});Object.assign(partialRoom.attributes.rooms[1]!,{occupancy:{children:0}});await job("booking-multi-partial","multi-partial",false,partialRoom,1);expect((await run()).deadLettered).toBe(1);const ignored=revision("ignored-cancel","booking-ignored","Agoda",0);ignored.attributes.status="cancelled";ignored.attributes.inserted_at="2026-08-20T12:00:00.500000Z";const ignoredJob=await job("booking-ignored","ignored-cancel",false,ignored);expect((await run()).succeeded).toBe(1);const olderCreate=revision("older-create","booking-ignored","Agoda");olderCreate.attributes.inserted_at="2026-08-20T12:00:00.400000Z";const olderJob=await job("booking-ignored","older-create",false,olderCreate);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT (SELECT count(*)::int FROM booking.guest_bookings WHERE source_booking_id=$3) bookings,cancel.job_metadata->'handledRevisions'->'ignored-cancel'->>'outcome' cancel_outcome,older.job_metadata->'handledRevisions'->'older-create'->>'outcome' older_outcome,(SELECT authoritative_revision_id FROM pms.channel_booking_revision_tombstones WHERE connection_id=$4 AND external_booking_id='booking-ignored' AND resolved_at IS NULL) watermark FROM platform.jobs cancel JOIN platform.jobs older ON older.id=$2 WHERE cancel.id=$1",[ignoredJob,olderJob,`channex:${P}:booking-ignored`,C])).rows[0]).toEqual({bookings:0,cancel_outcome:"ignored",older_outcome:"stale",watermark:"ignored-cancel"});const newerCreate=revision("newer-create","booking-ignored","Agoda");newerCreate.attributes.inserted_at="2026-08-20T12:00:00.600000Z";await job("booking-ignored","newer-create",false,newerCreate);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT (SELECT count(*)::int FROM booking.guest_bookings WHERE source_booking_id=$2) bookings,(SELECT resolved_at IS NOT NULL FROM pms.channel_booking_revision_tombstones WHERE connection_id=$1 AND external_booking_id='booking-ignored') resolved",[C,`channex:${P}:booking-ignored`])).rows[0]).toEqual({bookings:1,resolved:true});
    feed=[revision("lease-revision","booking-lease","BookingCom")];const leaseJob=await job("booking-lease","lease-revision",true,feed[0]!);let entered!:()=>void,release!:()=>void;const enteredP=new Promise<void>(resolve=>{entered=resolve}),releaseP=new Promise<void>(resolve=>{release=resolve}),held:typeof fetch=async(input,init)=>{if((init?.method??"GET")==="GET"){entered();await releaseP}return fetcher(input,init)},loser=runWith(held,"stale-worker");await enteredP;await db.query("UPDATE platform.jobs SET locked_at=now()-interval '6 minutes' WHERE id=$1",[leaseJob]);expect((await runWith(fetcher,"winner")).succeeded).toBe(1);release();await expect(loser).rejects.toThrow("lease_lost");expect((await db.query("SELECT array_agg(status ORDER BY attempt_number) statuses FROM platform.job_attempts WHERE job_id=$1",[leaseJob])).rows[0].statuses).toEqual(["timed_out","succeeded"]);
    const expired=await job("booking-expired","expired-revision",false,revision("expired-revision","booking-expired","Agoda"),1);await db.query("UPDATE platform.jobs SET status='running',attempts_count=1,locked_at=now()-interval '6 minutes',locked_by='gone' WHERE id=$1",[expired]);await db.query("INSERT INTO platform.job_attempts(job_id,attempt_number,status,worker_id) VALUES($1,1,'running','gone')",[expired]);expect((await run()).deadLettered).toBe(1);expect((await db.query("SELECT status,job_metadata->>'lastErrorCode' code,(SELECT count(*)::int FROM platform.product_audit_events WHERE job_id=job.id AND redacted_payload->>'failureCode'='worker_lease_expired') audits FROM platform.jobs job WHERE id=$1",[expired])).rows[0]).toEqual({status:"dead_lettered",code:"worker_lease_expired",audits:1});const abort=new AbortController();abort.abort();expect(await runWith(fetcher,"shutdown",abort.signal)).toEqual({succeeded:0,retryScheduled:0,deadLettered:0});
    await db.query("CREATE FUNCTION pms.vay1189_fail() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'forced rollback guest@example.test';END$$;CREATE TRIGGER vay1189_fail BEFORE INSERT ON pms.channel_booking_mappings FOR EACH ROW EXECUTE FUNCTION pms.vay1189_fail()");
    const evidenceBeforeRollback=(await db.query("SELECT count(*)::int count FROM booking.nightly_revenue_evidence WHERE property_id=$1",[P])).rows[0].count,rollback=await job("booking-rollback","rev-rollback",false,revision("rev-rollback","booking-rollback","Expedia"));expect((await run()).retryScheduled).toBe(1);expect((await db.query("SELECT count(*)::int count FROM booking.guest_bookings WHERE source_booking_id=$1",[`channex:${P}:booking-rollback`])).rows[0].count).toBe(0);expect((await db.query("SELECT count(*)::int count FROM booking.nightly_revenue_evidence WHERE property_id=$1",[P])).rows[0].count).toBe(evidenceBeforeRollback);
    await db.query("DROP TRIGGER vay1189_fail ON pms.channel_booking_mappings;DROP FUNCTION pms.vay1189_fail()");await db.query("UPDATE platform.jobs SET run_after=now() WHERE id=$1",[rollback]);expect((await run()).succeeded).toBe(1);
    const evidence=await db.query("SELECT bool_or(redacted_payload::text LIKE '%BookingCom%' OR redacted_payload::text LIKE '%example.test%' OR redacted_payload::text LIKE '%changed@example.test%') leaked FROM platform.product_audit_events WHERE redacted_payload->>'propertyId'=$1",[P]);expect(evidence.rows[0].leaked).toBe(false);expect((await db.query("SELECT status FROM platform.jobs WHERE resource_id='malformed'")).rows[0].status).toBe("dead_lettered");expect(calls.some(value=>value.includes("/ack"))).toBe(true);
  },60_000);

  function run(){return runWith(fetcher,"vay-1189")}function runWith(request:typeof fetch,workerId:string,signal?:AbortSignal){return runChannexBookingJobs(URL!,{apiBaseUrl:"https://app.channex.io",apiKey:"secret",ownsMutation:()=>owns,fetch:request,workerId,limit:1,signal})}
  function revenue(bookingId:string){return db.query(`SELECT count(*)::int lines,SUM(occupied_room_nights)::int occupied,SUM(gross_room_amount)::text amount,bool_and(source_kind='ota') ota,bool_and(evidence_quality='exact') exact,count(*) FILTER(WHERE economic_event='correction')::int corrections,count(*) FILTER(WHERE economic_event='occupancy_adjustment')::int adjustments,count(*) FILTER(WHERE economic_event='retained_charge')::int retained,count(*) FILTER(WHERE economic_event='refund')::int refunds FROM booking.nightly_revenue_evidence evidence JOIN booking.guest_bookings booking ON booking.id=evidence.guest_booking_id WHERE booking.source_booking_id=$1`,[`channex:${P}:${bookingId}`])}
  async function job(bookingId:string,revisionId:string,pullRequired:boolean,value:Record<string,unknown>,maxAttempts=5){const row=await db.query<{id:string}>(`INSERT INTO platform.jobs(job_key,queue_name,job_type,tenant_scope,resource_product,resource_type,resource_id,correlation_id,max_attempts,payload)
    VALUES($1,'pms.channex.webhooks','channex.ingest-booking','external','pms','channel_booking',$2,'vay-1189',$3,$4) RETURNING id::text`,[`vay-1189:${++sequence}`,bookingId,maxAttempts,{propertyId:P,providerPropertyId:EXTERNAL,channelBookingId:bookingId,revision:revisionId,revisionSource:pullRequired?"webhook_hint":"revision_feed",pullRequired,rawPayload:pullRequired?{event:"booking"}:{event:"booking",payload:value}}]);return row.rows[0]!.id;}
  function revision(id:string|number,bookingId:string,source:string|null,rooms=1){return {id,type:"booking_revision",attributes:{property_id:EXTERNAL,booking_id:bookingId,status:"new",arrival_date:"2026-09-01",departure_date:"2026-09-03",amount:`${rooms*120}.00`,currency:"EUR",inserted_at:new Date(Date.UTC(2026,7,20,12,0,sequence)).toISOString(),...(source?{ota_name:source}:{}),customer:{name:"Ada",surname:"Guest",mail:"guest@example.test",phone:"+100"},rooms:Array.from({length:rooms},()=>({room_type_id:"provider-room",rate_plan_id:"provider-rate",occupancy:{adults:1,children:0},days:{"2026-09-01":"60.00","2026-09-02":"60.00"}}))}};}
  function v2Fingerprint(value:ReturnType<typeof revision>){const a=value.attributes,parsed={rooms:a.rooms.map(room=>({externalRoomTypeId:room.room_type_id,externalRatePlanId:room.rate_plan_id,checkIn:a.arrival_date,checkOut:a.departure_date,adults:room.occupancy.adults,children:room.occupancy.children})),id:String(value.id),semanticRevision:null,providerPropertyId:a.property_id,bookingId:a.booking_id,status:"confirmed",checkIn:a.arrival_date,checkOut:a.departure_date,adults:a.rooms.length,children:0,roomCount:a.rooms.length,currency:a.currency,amount:a.amount,providerSource:a.ota_name??null,channel:"agoda",hasCustomer:true,hasEmail:true,hasPhone:true,firstName:"Ada",lastName:"Guest",email:"guest@example.test",phone:"+100",insertedAt:`${a.inserted_at.slice(0,19)}.${a.inserted_at.slice(20,23).padEnd(6,"0")}Z`};return createHash("sha256").update(JSON.stringify(parsed)).digest("hex")}
  async function cleanup(){await db.query("BEGIN;SET LOCAL session_replication_role=replica");await clearChannexAssignmentFixture(db,P);await db.query(`DROP TRIGGER IF EXISTS vay1189_fail ON pms.channel_booking_mappings;DROP FUNCTION IF EXISTS pms.vay1189_fail();BEGIN;SET LOCAL session_replication_role=replica;DELETE FROM platform.product_audit_events WHERE redacted_payload->>'propertyId'='${P}' OR target_resource_id='malformed';DELETE FROM platform.dead_letter_events WHERE job_id IN(SELECT id FROM platform.jobs WHERE payload->>'propertyId'='${P}' OR job_key LIKE 'vay-1189:%');DELETE FROM platform.job_attempts WHERE job_id IN(SELECT id FROM platform.jobs WHERE payload->>'propertyId'='${P}' OR job_key LIKE 'vay-1189:%');DELETE FROM platform.jobs WHERE payload->>'propertyId'='${P}' OR job_key LIKE 'vay-1189:%';DELETE FROM pms.channel_booking_mappings WHERE property_id='${P}';DELETE FROM booking.guest_bookings WHERE property_id='${P}';DELETE FROM pms.channel_connections WHERE property_id='${P}';DELETE FROM pms.channel_binding_claims WHERE property_id='${P}';DELETE FROM hotel_catalog.properties WHERE id='${P}';COMMIT`);}
});
