export const CHANNEX_MANAGEMENT_WORKER_ROLE = "vayada_next_channex_management_worker";

// VAY-2041: exact effective grants for selected published offers and ARI.
// Column UPDATE on source identities permits row locks; restrictive WITH CHECK
// policies forbid actual source mutation. No grant is installed by this module.
// prettier-ignore
export const channexManagementWorkerPrivileges: Record<string, Record<string, true | string[]>> = {
  "platform.channex_management_worker_properties": { SELECT: true },
  "platform.external_webhook_events": { SELECT: ["id", "provider"] },
  "platform.jobs": { SELECT: true, INSERT: ["job_key", "queue_name", "job_type", "max_attempts", "tenant_scope", "property_id", "resource_product", "resource_type", "resource_id", "payload", "job_metadata"], UPDATE: ["status", "attempts_count", "max_attempts", "run_after", "locked_at", "locked_by", "finished_at", "updated_at", "job_metadata"] },
  "platform.job_attempts": { SELECT: true, INSERT: ["job_id", "attempt_number", "status", "worker_id", "started_at", "error_metadata"], UPDATE: ["status", "finished_at", "error_type", "error_message", "retry_after", "error_metadata"] },
  "platform.dead_letter_events": { SELECT: true, INSERT: ["source_kind", "job_id", "job_attempt_id", "tenant_scope", "property_id", "resource_product", "resource_type", "resource_id", "correlation_id", "idempotency_key_hash", "reason_code", "failure_summary", "failure_payload"] },
  "platform.idempotency_keys": { SELECT: true, UPDATE: ["status", "completed_at", "response_status_code", "response_resource_product", "response_resource_type", "response_resource_id"] },
  "platform.product_audit_events": { SELECT: true, INSERT: ["audit_key", "product", "action", "occurred_at", "tenant_scope", "property_id", "actor_type", "target_resource_product", "target_resource_type", "target_resource_id", "job_id", "correlation_id", "redacted_payload", "audit_metadata"] },
  "hotel_catalog.properties": { SELECT: true, UPDATE: ["id"] },
  "hotel_catalog.property_locations": { SELECT: true, UPDATE: ["property_id"] },
  "identity.organizations": { SELECT: ["id", "kind", "status"], UPDATE: ["id"] },
  "identity.organization_resource_links": { SELECT: ["organization_id", "product", "resource_type", "resource_id", "relationship", "status"], UPDATE: ["organization_id"] },
  "identity.product_entitlements": { SELECT: ["organization_id", "product", "entitlement_key", "status", "resource_product", "resource_type", "resource_id", "starts_at", "expires_at"], UPDATE: ["organization_id"] },
  "finance.payment_settings": { SELECT: true, UPDATE: ["property_id"] },
  "finance.payment_provider_accounts": { SELECT: true, UPDATE: ["id"] },
  "finance.online_card_execution_evidence": { SELECT: true, UPDATE: ["id"] },
  "finance.online_card_readiness": { SELECT: ["property_id", "currency_eligible"] },
  "booking.pricing_v2_offer_term_heads": { SELECT: true, UPDATE: ["property_id"] },
  "booking.pricing_v2_offer_terms": { SELECT: true },
  "booking.fixed_charge_heads": { SELECT: true, UPDATE: ["property_id"] },
  "booking.fixed_charge_revisions": { SELECT: true, UPDATE: ["property_id"] },
  "booking.same_day_booking_policies": { SELECT: true },
  "pms.room_types": { SELECT: true, UPDATE: ["id"] },
  "pms.rooms": { SELECT: true },
  "pms.room_type_closures": { SELECT: true },
  "pms.property_pricing_settings": { SELECT: true },
  "pms.rate_plans": { SELECT: true },
  "pms.recurring_pricing_sources": { SELECT: true },
  "pms.recurring_pricing_source_room_values": { SELECT: true },
  "pms.channel_date_prices": { SELECT: true },
  "pms.pricing_v2_heads": { SELECT: true },
  "pms.pricing_v2_revisions": { SELECT: true },
  "pms.pricing_v2_rooms": { SELECT: true },
  "pms.pricing_v2_charge_declarations": { SELECT: true },
  "pms.operating_calendar_revisions": { SELECT: true, UPDATE: ["property_id"] },
  "pms.operating_calendar_recurring_periods": { SELECT: true },
  "pms.operating_calendar_room_bindings": { SELECT: true },
  "pms.inventory_days": { SELECT: true, UPDATE: ["property_id"] },
  "pms.inventory_materialization_coverage": { SELECT: true, UPDATE: ["property_id"] },
  "pms.channel_binding_claims": { SELECT: true, UPDATE: ["id"] },
  "pms.channel_connections": { SELECT: true, UPDATE: ["external_property_id", "messaging_app_installed", "last_booking_sync_at", "last_ari_sync_at", "connection_metadata", "updated_at"] },
  "pms.channel_room_type_mappings": { SELECT: true, UPDATE: ["id"] },
  "pms.channel_rate_plan_mappings": { SELECT: true },
  "pms.channel_sync_status": { SELECT: true, INSERT: ["property_id", "connection_id", "sync_domain", "status", "last_attempt_at", "last_success_at", "last_error_code", "last_error_message", "retry_after"], UPDATE: ["status", "last_attempt_at", "last_success_at", "last_error_code", "last_error_message", "retry_after", "updated_at"] },
  "pms.channex_ari_schedule_sources": { SELECT: true, INSERT: ["property_id", "fingerprint"], UPDATE: ["fingerprint", "revision"] },
  "pms.channex_offer_targets": { SELECT: true, INSERT: ["property_id", "connection_id", "room_type_id", "offer_id"], UPDATE: ["next_version", "active_version"] },
  "pms.channex_offer_target_intents": { SELECT: true, INSERT: ["target_id", "operation_key", "proposal"], UPDATE: ["status", "result_evidence"] },
  "pms.channex_offer_target_versions": { SELECT: true, INSERT: ["target_id", "version", "intent_id", "binding_generation", "external_property_id", "external_room_type_id", "external_rate_plan_id", "configuration", "readback_evidence"] },
  "pms.channex_external_rate_owners": { SELECT: true, INSERT: ["connection_id", "external_rate_plan_id", "owner_kind", "owner_id", "legacy_identity"] },
  "pms.channex_offer_create_attempts": { SELECT: true, INSERT: ["target_id", "intent_id", "version", "binding_generation", "external_property_id", "external_room_type_id", "request_body", "job_attempt_id", "worker_id"], UPDATE: ["state", "external_rate_plan_id"] },
  "pms.channex_offer_create_receipts": { SELECT: true, INSERT: ["id", "attempt_id", "job_attempt_id", "worker_id", "outcome", "http_status", "provider_request_id", "identity_evidence", "has_warnings"] },
  "pms.channex_offer_ari_attempts": { SELECT: true, INSERT: ["creation_attempt_id", "job_attempt_id", "worker_id", "service_date", "request_body"], UPDATE: ["state", "reconciliation_evidence"] },
  "pms.channex_offer_ari_receipts": { SELECT: true, INSERT: ["id", "attempt_id", "job_attempt_id", "worker_id", "outcome", "http_status", "provider_request_id", "task_ids", "has_warnings", "warning_reason"] },
  "pms.channex_room_availability_attempts": { SELECT: true, INSERT: ["mapping_id", "job_attempt_id", "worker_id", "service_date", "available_count", "inventory_evidence", "request_body", "inventory_evidence_sha256"], UPDATE: ["state", "reconciliation_evidence"] },
  "pms.channex_room_availability_receipts": { SELECT: true, INSERT: ["id", "attempt_id", "job_attempt_id", "worker_id", "outcome", "http_status", "provider_request_id", "task_ids", "has_warnings", "warning_reason"] },
  "pms.channex_room_availability_reconciliation_attestations": { SELECT: true, INSERT: ["attempt_id", "receipt_id", "inventory_evidence_sha256", "observations_sha256", "reconciliation_evidence"] },
};
