import pg from "pg";
import {
  seedChannexAssignmentFixture,
  clearChannexAssignmentFixture,
} from "./channexAssignmentTestFixture.js";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { runChannexBookingJobs } from "./channexBookings.js";

const URL = process.env["TEST_DATABASE_URL"],
  P = "11890000-0000-4000-8000-000000000001",
  C = "11890000-0000-4000-8000-000000000002",
  EXTERNAL = "chx-vay-1189";
if (URL && !/(^|[_-])(test|verify)([_-]|$)/i.test(new globalThis.URL(URL).pathname))
  throw new Error("Refusing non-test database");

// prettier-ignore
describe.skipIf(!URL)("Channex booking worker (PostgreSQL)",()=>{
  const db=new pg.Pool({connectionString:URL??"postgresql://disabled",max:4});let sequence=0,feed:Record<string,unknown>[]=[],owns=true,loseAck:string|null=null;const calls:string[]=[],acked=new Set<string>();
  const fetcher:typeof fetch=async(input,init)=>{const url=String(input),method=init?.method??"GET";calls.push(`${method} ${url}`);if(method==="GET")return Response.json({data:feed});const revisionId=url.split("/").at(-2)!,durable=await db.query("SELECT 1 FROM platform.jobs WHERE job_metadata->'handledRevisions' ? $1 LIMIT 1",[revisionId]);expect(durable.rowCount).toBe(1);const repeated=acked.has(revisionId);acked.add(revisionId);if(loseAck===revisionId){loseAck=null;throw new Error("ACK response lost")}return new Response(null,{status:repeated?404:204});};
  beforeAll(async()=>{await cleanup();await db.query("INSERT INTO hotel_catalog.properties(id,public_id,display_name) VALUES($1,'vay-1189','Channex worker')",[P]);await db.query("INSERT INTO pms.channel_binding_claims(property_id,provider,external_property_id,claim_state,claim_source) VALUES($1,'channex',$2,'active','repair')",[P,EXTERNAL]);await db.query("INSERT INTO pms.channel_connections(id,property_id,provider,connection_status,external_property_id) VALUES($2,$1,'channex','connected',$3)",[P,C,EXTERNAL]);await seedChannexAssignmentFixture(db,P);});
  afterAll(async()=>{await cleanup();await db.end();});

  it("pulls, attributes, replays, retries atomically, dead-letters, and acknowledges only durable revisions",async()=>{
    feed=[revision("rev-booking","booking-1","BookingCom",2),revision(8,"booking-1","BookingCom")];const first=await job("booking-1","unknown",true,feed[0]!);expect(await run()).toEqual({succeeded:1,retryScheduled:0,deadLettered:0});
    const saved=await db.query(`SELECT booking_channel,(SELECT count(*)::int FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id) mappings,
      (SELECT mapping_metadata->>'providerSource' FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id LIMIT 1) source
      FROM booking.guest_bookings booking WHERE source_booking_id=$1`,[`channex:${P}:booking-1`]);expect(saved.rows[0]).toEqual({booking_channel:"booking_com",mappings:2,source:"BookingCom"});
    feed=[];await db.query("UPDATE platform.jobs SET status='pending',finished_at=NULL,run_after=now() WHERE id=$1",[first]);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT count(*)::int count FROM booking.guest_bookings WHERE source_booking_id=$1",[`channex:${P}:booking-1`])).rows[0].count).toBe(1);
    const partial=revision("partial-contact","booking-1","Expedia");partial.attributes.inserted_at="2026-08-20T12:00:00.123400Z";Object.assign(partial.attributes,{customer:{name:"Partial"}});await job("booking-1","partial-contact",false,partial);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT first_name,email,phone FROM booking.booking_guests guest JOIN booking.guest_bookings booking ON booking.id=guest.guest_booking_id WHERE booking.source_booking_id=$1",[`channex:${P}:booking-1`])).rows[0]).toEqual({first_name:"Partial",email:"guest@example.test",phone:"+100"});
    const changed=revision(9,"booking-1","Expedia",0);changed.attributes.status="cancelled";changed.attributes.inserted_at="2026-08-20T12:00:00.123456Z";changed.attributes.customer={name:"Grace",surname:"Changed",mail:"changed@example.test",phone:"+123"};await job("booking-1","9",false,changed);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT lifecycle_status,booking_channel,room_count,(SELECT count(*)::int FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id AND sync_status='active') active,(SELECT first_name FROM booking.booking_guests WHERE guest_booking_id=booking.id AND guest_role='booker') guest,(SELECT email FROM booking.booking_guests WHERE guest_booking_id=booking.id AND guest_role='booker') email,(SELECT mapping_metadata->>'providerSource' FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id LIMIT 1) original,(SELECT mapping_metadata->>'latestProviderSource' FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id LIMIT 1) latest FROM booking.guest_bookings booking WHERE source_booking_id=$1",[`channex:${P}:booking-1`])).rows[0]).toEqual({lifecycle_status:"canceled",booking_channel:"booking_com",room_count:1,active:1,guest:"Grace",email:"changed@example.test",original:"BookingCom",latest:"Expedia"});
    const older=revision(7,"booking-1","Airbnb");older.attributes.inserted_at="2026-08-20T12:00:00.123123Z";feed=[older];loseAck="7";const stale=await job("booking-1","7",true,older);expect((await run()).retryScheduled).toBe(1);feed=[];await db.query("UPDATE platform.jobs SET run_after=now() WHERE id=$1",[stale]);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT booking.booking_channel,booking.lifecycle_status,guest.first_name,(SELECT external_revision_id FROM pms.channel_booking_mappings WHERE guest_booking_id=booking.id AND sync_status='active' LIMIT 1) revision,job.job_metadata->'handledRevisions'->'7'->>'outcome' outcome,length(job.job_metadata->'handledRevisions'->'7'->>'fingerprint') fingerprint FROM booking.guest_bookings booking JOIN booking.booking_guests guest ON guest.guest_booking_id=booking.id AND guest.guest_role='booker' JOIN platform.jobs job ON job.id=$1::uuid WHERE booking.source_booking_id=$2",[stale,`channex:${P}:booking-1`])).rows[0]).toEqual({booking_channel:"booking_com",lifecycle_status:"canceled",first_name:"Grace",revision:"9",outcome:"stale",fingerprint:64});
    const providerShaped=revision("rev-other","booking-2","Hostelworld");providerShaped.attributes.inserted_at="2019-04-23T10:03:29.335485";await job("booking-2","rev-other",false,providerShaped);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT mapping_metadata->>'providerInsertedAt' inserted FROM pms.channel_booking_mappings WHERE connection_id=$1 AND external_booking_id='booking-2'",[C])).rows[0].inserted).toBe("2019-04-23T10:03:29.335485Z");
    await job("booking-3","rev-unknown",false,revision("rev-unknown","booking-3",null));expect((await run()).succeeded).toBe(1);const expanded=revision("rev-unknown-expanded","booking-3","Expedia",2);await job("booking-3","rev-unknown-expanded",false,expanded);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT count(*)::int mappings,count(*) FILTER(WHERE mapping_metadata->>'providerSource' IS NOT NULL)::int sources FROM pms.channel_booking_mappings WHERE connection_id=$1 AND external_booking_id='booking-3'",[C])).rows[0]).toEqual({mappings:2,sources:0});
    for(const [id,source] of [["4","Airbnb"],["5","Expedia.com"],["6","Agoda"]] as const){await job(`booking-${id}`,`rev-${id}`,false,revision(`rev-${id}`,`booking-${id}`,source));expect((await run()).succeeded).toBe(1)}expect((await db.query("SELECT source_booking_id,booking_channel FROM booking.guest_bookings WHERE property_id=$1 ORDER BY source_booking_id",[P])).rows.map(row=>row.booking_channel)).toEqual(["booking_com","other_ota","unknown","airbnb","expedia","agoda"]);
    for(const [hint,key] of [[41,"revision"],["42","revision_number"]] as const){const semantic=revision(`semantic-${hint}`,`booking-hint-${hint}`,"Agoda");Object.assign(semantic.attributes,{[key]:hint});if(hint===41){Object.assign(semantic.attributes,{occupancy:{adults:1,children:0}});Reflect.deleteProperty(semantic.attributes.rooms[0]!,"occupancy");loseAck=String(semantic.id)}feed=[semantic];const semanticJob=await job(`booking-hint-${hint}`,String(hint),true,semantic);expect((await run())[hint===41?"retryScheduled":"succeeded"]).toBe(1);if(hint===41){feed=[];await db.query("UPDATE platform.jobs SET run_after=now() WHERE id=$1",[semanticJob]);expect((await run()).succeeded).toBe(1)}}
    const feedFirst=revision("alias-feed-first","booking-alias-feed","Agoda");Object.assign(feedFirst.attributes,{revision:51});await job("booking-alias-feed","alias-feed-first",false,feedFirst);expect((await run()).succeeded).toBe(1);feed=[];await job("booking-alias-feed","51",true,feedFirst);expect((await run()).succeeded).toBe(1);const webhookFirst=revision("alias-webhook-first","booking-alias-webhook","Agoda");Object.assign(webhookFirst.attributes,{revision_number:"52"});feed=[webhookFirst];await job("booking-alias-webhook","52",true,webhookFirst);expect((await run()).succeeded).toBe(1);feed=[];await job("booking-alias-webhook","alias-webhook-first",false,webhookFirst);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT count(DISTINCT alias)::int count FROM platform.jobs evidence,jsonb_each(evidence.job_metadata->'handledRevisions') handled,jsonb_array_elements_text(handled.value->'aliases') alias WHERE evidence.payload->>'propertyId'=$1 AND alias IN('51','alias-feed-first','52','alias-webhook-first')",[P])).rows[0].count).toBe(4);

    owns=false;const frozen=await job("booking-frozen","rev-frozen",false,revision("rev-frozen","booking-frozen","Agoda"),1);expect((await run()).deadLettered).toBe(1);owns=true;expect((await db.query("SELECT status,(SELECT count(*)::int FROM platform.dead_letter_events WHERE job_id=job.id) dead FROM platform.jobs job WHERE id=$1",[frozen])).rows[0]).toEqual({status:"dead_lettered",dead:1});
    await db.query("INSERT INTO platform.jobs(job_key,queue_name,job_type,tenant_scope,resource_product,resource_type,resource_id,payload) VALUES($1,'pms.channex.webhooks','channex.ingest-booking','external','pms','channel_booking','malformed','{}')",[`vay-1189:${++sequence}`]);expect((await run()).deadLettered).toBe(1);
    const missing=revision("missing-rooms","booking-missing","Agoda");Reflect.deleteProperty(missing.attributes,"rooms");await job("booking-missing","missing-rooms",false,missing,1);expect((await run()).deadLettered).toBe(1);const bad=revision("bad-occupancy","booking-bad","Agoda");bad.attributes.rooms[0]!.occupancy.adults=-1;await job("booking-bad","bad-occupancy",false,bad,1);expect((await run()).deadLettered).toBe(1);const empty=revision("multi-empty","booking-multi-empty","Agoda",2);Object.assign(empty.attributes,{occupancy:{adults:2,children:0}});empty.attributes.rooms.forEach(room=>Object.assign(room,{occupancy:{}}));await job("booking-multi-empty","multi-empty",false,empty,1);expect((await run()).deadLettered).toBe(1);const partialRoom=revision("multi-partial","booking-multi-partial","Agoda",2);Object.assign(partialRoom.attributes,{occupancy:{adults:2,children:0}});Object.assign(partialRoom.attributes.rooms[1]!,{occupancy:{children:0}});await job("booking-multi-partial","multi-partial",false,partialRoom,1);expect((await run()).deadLettered).toBe(1);const ignored=revision("ignored-cancel","booking-ignored","Agoda",0);ignored.attributes.status="cancelled";ignored.attributes.inserted_at="2026-08-20T12:00:00.500000Z";const ignoredJob=await job("booking-ignored","ignored-cancel",false,ignored);expect((await run()).succeeded).toBe(1);const olderCreate=revision("older-create","booking-ignored","Agoda");olderCreate.attributes.inserted_at="2026-08-20T12:00:00.400000Z";const olderJob=await job("booking-ignored","older-create",false,olderCreate);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT (SELECT count(*)::int FROM booking.guest_bookings WHERE source_booking_id=$3) bookings,cancel.job_metadata->'handledRevisions'->'ignored-cancel'->>'outcome' cancel_outcome,older.job_metadata->'handledRevisions'->'older-create'->>'outcome' older_outcome,(SELECT authoritative_revision_id FROM pms.channel_booking_revision_tombstones WHERE connection_id=$4 AND external_booking_id='booking-ignored' AND resolved_at IS NULL) watermark FROM platform.jobs cancel JOIN platform.jobs older ON older.id=$2 WHERE cancel.id=$1",[ignoredJob,olderJob,`channex:${P}:booking-ignored`,C])).rows[0]).toEqual({bookings:0,cancel_outcome:"ignored",older_outcome:"stale",watermark:"ignored-cancel"});const newerCreate=revision("newer-create","booking-ignored","Agoda");newerCreate.attributes.inserted_at="2026-08-20T12:00:00.600000Z";await job("booking-ignored","newer-create",false,newerCreate);expect((await run()).succeeded).toBe(1);expect((await db.query("SELECT (SELECT count(*)::int FROM booking.guest_bookings WHERE source_booking_id=$2) bookings,(SELECT resolved_at IS NOT NULL FROM pms.channel_booking_revision_tombstones WHERE connection_id=$1 AND external_booking_id='booking-ignored') resolved",[C,`channex:${P}:booking-ignored`])).rows[0]).toEqual({bookings:1,resolved:true});
    feed=[revision("lease-revision","booking-lease","BookingCom")];const leaseJob=await job("booking-lease","lease-revision",true,feed[0]!);let entered!:()=>void,release!:()=>void;const enteredP=new Promise<void>(resolve=>{entered=resolve}),releaseP=new Promise<void>(resolve=>{release=resolve}),held:typeof fetch=async(input,init)=>{if((init?.method??"GET")==="GET"){entered();await releaseP}return fetcher(input,init)},loser=runWith(held,"stale-worker");await enteredP;await db.query("UPDATE platform.jobs SET locked_at=now()-interval '6 minutes' WHERE id=$1",[leaseJob]);expect((await runWith(fetcher,"winner")).succeeded).toBe(1);release();await expect(loser).rejects.toThrow("lease_lost");expect((await db.query("SELECT array_agg(status ORDER BY attempt_number) statuses FROM platform.job_attempts WHERE job_id=$1",[leaseJob])).rows[0].statuses).toEqual(["timed_out","succeeded"]);
    const expired=await job("booking-expired","expired-revision",false,revision("expired-revision","booking-expired","Agoda"),1);await db.query("UPDATE platform.jobs SET status='running',attempts_count=1,locked_at=now()-interval '6 minutes',locked_by='gone' WHERE id=$1",[expired]);await db.query("INSERT INTO platform.job_attempts(job_id,attempt_number,status,worker_id) VALUES($1,1,'running','gone')",[expired]);expect((await run()).deadLettered).toBe(1);expect((await db.query("SELECT status,job_metadata->>'lastErrorCode' code,(SELECT count(*)::int FROM platform.product_audit_events WHERE job_id=job.id AND redacted_payload->>'failureCode'='worker_lease_expired') audits FROM platform.jobs job WHERE id=$1",[expired])).rows[0]).toEqual({status:"dead_lettered",code:"worker_lease_expired",audits:1});const abort=new AbortController();abort.abort();expect(await runWith(fetcher,"shutdown",abort.signal)).toEqual({succeeded:0,retryScheduled:0,deadLettered:0});
    await db.query("CREATE FUNCTION pms.vay1189_fail() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'forced rollback guest@example.test';END$$;CREATE TRIGGER vay1189_fail BEFORE INSERT ON pms.channel_booking_mappings FOR EACH ROW EXECUTE FUNCTION pms.vay1189_fail()");
    const rollback=await job("booking-rollback","rev-rollback",false,revision("rev-rollback","booking-rollback","Expedia"));expect((await run()).retryScheduled).toBe(1);expect((await db.query("SELECT count(*)::int count FROM booking.guest_bookings WHERE source_booking_id=$1",[`channex:${P}:booking-rollback`])).rows[0].count).toBe(0);
    await db.query("DROP TRIGGER vay1189_fail ON pms.channel_booking_mappings;DROP FUNCTION pms.vay1189_fail()");await db.query("UPDATE platform.jobs SET run_after=now() WHERE id=$1",[rollback]);expect((await run()).succeeded).toBe(1);
    const evidence=await db.query("SELECT bool_or(redacted_payload::text LIKE '%BookingCom%' OR redacted_payload::text LIKE '%example.test%' OR redacted_payload::text LIKE '%changed@example.test%') leaked FROM platform.product_audit_events WHERE redacted_payload->>'propertyId'=$1",[P]);expect(evidence.rows[0].leaked).toBe(false);expect((await db.query("SELECT status FROM platform.jobs WHERE resource_id='malformed'")).rows[0].status).toBe("dead_lettered");expect(calls.some(value=>value.includes("/ack"))).toBe(true);
  },20_000);

  function run(){return runWith(fetcher,"vay-1189")}function runWith(request:typeof fetch,workerId:string,signal?:AbortSignal){return runChannexBookingJobs(URL!,{apiBaseUrl:"https://app.channex.io",apiKey:"secret",ownsMutation:()=>owns,fetch:request,workerId,limit:1,signal})}
  async function job(bookingId:string,revisionId:string,pullRequired:boolean,value:Record<string,unknown>,maxAttempts=5){const row=await db.query<{id:string}>(`INSERT INTO platform.jobs(job_key,queue_name,job_type,tenant_scope,resource_product,resource_type,resource_id,correlation_id,max_attempts,payload)
    VALUES($1,'pms.channex.webhooks','channex.ingest-booking','external','pms','channel_booking',$2,'vay-1189',$3,$4) RETURNING id::text`,[`vay-1189:${++sequence}`,bookingId,maxAttempts,{propertyId:P,providerPropertyId:EXTERNAL,channelBookingId:bookingId,revision:revisionId,revisionSource:pullRequired?"webhook_hint":"revision_feed",pullRequired,rawPayload:pullRequired?{event:"booking"}:{event:"booking",payload:value}}]);return row.rows[0]!.id;}
  function revision(id:string|number,bookingId:string,source:string|null,rooms=1){return {id,type:"booking_revision",attributes:{property_id:EXTERNAL,booking_id:bookingId,status:"new",arrival_date:"2026-09-01",departure_date:"2026-09-03",amount:"240.00",currency:"EUR",inserted_at:new Date(Date.UTC(2026,7,20,12,0,sequence)).toISOString(),...(source?{ota_name:source}:{}),customer:{name:"Ada",surname:"Guest",mail:"guest@example.test",phone:"+100"},rooms:Array.from({length:rooms},()=>({room_type_id:"provider-room",rate_plan_id:"provider-rate",occupancy:{adults:1,children:0}}))}};}
  async function cleanup(){await db.query("BEGIN;SET LOCAL session_replication_role=replica");await clearChannexAssignmentFixture(db,P);await db.query(`DROP TRIGGER IF EXISTS vay1189_fail ON pms.channel_booking_mappings;DROP FUNCTION IF EXISTS pms.vay1189_fail();BEGIN;SET LOCAL session_replication_role=replica;DELETE FROM platform.product_audit_events WHERE redacted_payload->>'propertyId'='${P}' OR target_resource_id='malformed';DELETE FROM platform.dead_letter_events WHERE job_id IN(SELECT id FROM platform.jobs WHERE payload->>'propertyId'='${P}' OR job_key LIKE 'vay-1189:%');DELETE FROM platform.job_attempts WHERE job_id IN(SELECT id FROM platform.jobs WHERE payload->>'propertyId'='${P}' OR job_key LIKE 'vay-1189:%');DELETE FROM platform.jobs WHERE payload->>'propertyId'='${P}' OR job_key LIKE 'vay-1189:%';DELETE FROM pms.channel_booking_mappings WHERE property_id='${P}';DELETE FROM booking.guest_bookings WHERE property_id='${P}';DELETE FROM pms.channel_connections WHERE property_id='${P}';DELETE FROM pms.channel_binding_claims WHERE property_id='${P}';DELETE FROM hotel_catalog.properties WHERE id='${P}';COMMIT`);}
});
