export type FinanceColumn = readonly [jsonKey: string, sqlName: string, type: string];
export type FinanceTableDefinition = {
  table: string;
  key: readonly string[];
  freshness: string;
  columns: readonly FinanceColumn[];
};

const c = (jsonKey: string, sqlName: string, type: string): FinanceColumn => [
  jsonKey,
  sqlName,
  type,
];
const id = c("id", "id", "uuid");
const property = c("propertyId", "property_id", "uuid");
const created = c("createdAt", "created_at", "timestamptz");
const updated = c("updatedAt", "updated_at", "timestamptz");
const source = (kind: string) =>
  [
    c("sourceSystem", "source_system", "text"),
    c(`source${kind}Id`, `source_${kind.toLowerCase()}_id`, "text"),
  ] as const;

export const PRODUCTION_FINANCE_WRITE_ORDER = [
  "payment_provider_accounts",
  "payment_settings",
  "payout_settings",
  "payments",
  "payouts",
  "commission_rules",
  "commission_rate_changes",
  "billing_entitlements",
] as const;

const table = (
  name: string,
  columns: readonly FinanceColumn[],
  freshness = "updated_at",
  key: readonly string[] = ["id"],
): FinanceTableDefinition => ({ table: `finance.${name}`, columns, freshness, key });

export const PRODUCTION_FINANCE_TABLES: Record<string, FinanceTableDefinition> = {
  payment_provider_accounts: table("payment_provider_accounts", [
    id,
    property,
    c("organizationId", "organization_id", "uuid"),
    c("accountScope", "account_scope", "text"),
    c("provider", "provider", "text"),
    c("providerAccountId", "provider_account_id", "text"),
    c("status", "status", "text"),
    c("onboardingStatus", "onboarding_status", "text"),
    c("chargesEnabled", "charges_enabled", "boolean"),
    c("payoutsEnabled", "payouts_enabled", "boolean"),
    c("defaultCurrency", "default_currency", "text"),
    c("capabilities", "capabilities", "text[]"),
    c("accountMetadata", "account_metadata", "jsonb"),
    c("sensitiveConfigRef", "sensitive_config_ref", "text"),
    created,
    updated,
  ]),
  payment_settings: table(
    "payment_settings",
    [
      property,
      c("providerAccountId", "provider_account_id", "uuid"),
      c("paymentsEnabled", "payments_enabled", "boolean"),
      c("acceptedMethods", "accepted_methods", "text[]"),
      c("defaultCurrency", "default_currency", "text"),
      c("depositPolicy", "deposit_policy", "jsonb"),
      c("refundPolicy", "refund_policy", "jsonb"),
      c("taxPolicy", "tax_policy", "jsonb"),
      c("statementDescriptor", "statement_descriptor", "text"),
      c("requiresManualReview", "requires_manual_review", "boolean"),
      ...source("Settings"),
      created,
      updated,
    ],
    "updated_at",
    ["property_id"],
  ),
  payout_settings: table("payout_settings", [
    id,
    property,
    c("organizationId", "organization_id", "uuid"),
    c("propertyProviderAccountId", "property_provider_account_id", "uuid"),
    c("organizationProviderAccountId", "organization_provider_account_id", "uuid"),
    c("ownerScope", "owner_scope", "text"),
    c("payoutMethod", "payout_method", "text"),
    c("destinationCountryCode", "destination_country_code", "text"),
    c("defaultCurrency", "default_currency", "text"),
    c("status", "status", "text"),
    c("schedule", "schedule", "jsonb"),
    c("payoutPreferences", "payout_preferences", "jsonb"),
    c("sensitiveDestinationRef", "sensitive_destination_ref", "text"),
    ...source("Settings"),
    created,
    updated,
  ]),
  payments: table("payments", [
    id,
    property,
    c("organizationId", "organization_id", "uuid"),
    c("guestBookingId", "guest_booking_id", "uuid"),
    c("providerAccountId", "provider_account_id", "uuid"),
    ...source("Payment"),
    c("idempotencyKey", "idempotency_key", "text"),
    c("paymentKind", "payment_kind", "text"),
    c("paymentMethod", "payment_method", "text"),
    c("status", "status", "text"),
    c("amount", "amount", "numeric"),
    c("feeAmount", "fee_amount", "numeric"),
    c("netAmount", "net_amount", "numeric"),
    c("refundedAmount", "refunded_amount", "numeric"),
    c("currency", "currency", "text"),
    c("providerTransactionId", "provider_transaction_id", "text"),
    c("providerPaymentIntentId", "provider_payment_intent_id", "text"),
    c("processorFeeBreakdown", "processor_fee_breakdown", "jsonb"),
    c("riskReview", "risk_review", "jsonb"),
    c("paymentMetadata", "payment_metadata", "jsonb"),
    c("visibilityClass", "visibility_class", "text"),
    c("authorizedAt", "authorized_at", "timestamptz"),
    c("paidAt", "paid_at", "timestamptz"),
    c("failedAt", "failed_at", "timestamptz"),
    c("disputedAt", "disputed_at", "timestamptz"),
    c("piiRetentionUntil", "pii_retention_until", "date"),
    created,
    updated,
  ]),
  payouts: table("payouts", [
    id,
    c("payoutSettingId", "payout_setting_id", "uuid"),
    c("paymentId", "payment_id", "uuid"),
    c("guestBookingId", "guest_booking_id", "uuid"),
    c("propertyProviderAccountId", "property_provider_account_id", "uuid"),
    c("organizationProviderAccountId", "organization_provider_account_id", "uuid"),
    c("ownerScope", "owner_scope", "text"),
    property,
    c("organizationId", "organization_id", "uuid"),
    c("relatedPropertyId", "related_property_id", "uuid"),
    ...source("Payout"),
    c("payoutStatus", "payout_status", "text"),
    c("amount", "amount", "numeric"),
    c("feeAmount", "fee_amount", "numeric"),
    c("netAmount", "net_amount", "numeric"),
    c("currency", "currency", "text"),
    c("periodStart", "period_start", "date"),
    c("periodEnd", "period_end", "date"),
    c("providerPayoutId", "provider_payout_id", "text"),
    c("scheduledAt", "scheduled_at", "timestamptz"),
    c("paidAt", "paid_at", "timestamptz"),
    c("failedAt", "failed_at", "timestamptz"),
    c("failureCode", "failure_code", "text"),
    c("retryCount", "retry_count", "integer"),
    c("payoutMetadata", "payout_metadata", "jsonb"),
    created,
    updated,
  ]),
  commission_rules: table("commission_rules", [
    id,
    property,
    c("organizationId", "organization_id", "uuid"),
    c("ruleScope", "rule_scope", "text"),
    c("product", "product", "text"),
    c("commissionType", "commission_type", "text"),
    c("percentageRate", "percentage_rate", "numeric"),
    c("fixedAmount", "fixed_amount", "numeric"),
    c("currency", "currency", "text"),
    c("status", "status", "text"),
    c("startsAt", "starts_at", "timestamptz"),
    c("endsAt", "ends_at", "timestamptz"),
    ...source("Rule"),
    c("ruleMetadata", "rule_metadata", "jsonb"),
    created,
    updated,
    c("affiliateId", "affiliate_id", "text"),
    c("otaChannel", "ota_channel", "text"),
    c("revision", "revision", "integer"),
  ]),
  commission_rate_changes: table(
    "commission_rate_changes",
    [
      id,
      c("commissionRuleId", "commission_rule_id", "uuid"),
      c("changedByUserId", "changed_by_user_id", "uuid"),
      c("previousPercentageRate", "previous_percentage_rate", "numeric"),
      c("newPercentageRate", "new_percentage_rate", "numeric"),
      c("previousFixedAmount", "previous_fixed_amount", "numeric"),
      c("newFixedAmount", "new_fixed_amount", "numeric"),
      c("currency", "currency", "text"),
      c("reason", "reason", "text"),
      c("effectiveAt", "effective_at", "timestamptz"),
      c("changedAt", "changed_at", "timestamptz"),
      c("changeMetadata", "change_metadata", "jsonb"),
    ],
    "changed_at",
  ),
  billing_entitlements: table("billing_entitlements", [
    id,
    c("organizationId", "organization_id", "uuid"),
    property,
    c("product", "product", "text"),
    c("entitlementKey", "entitlement_key", "text"),
    c("billingStatus", "billing_status", "text"),
    c("planKey", "plan_key", "text"),
    c("seatCount", "seat_count", "integer"),
    c("billingProvider", "billing_provider", "text"),
    c("billingCustomerRef", "billing_customer_ref", "text"),
    c("billingSubscriptionRef", "billing_subscription_ref", "text"),
    c("billingPeriodStart", "billing_period_start", "date"),
    c("billingPeriodEnd", "billing_period_end", "date"),
    c("startsAt", "starts_at", "timestamptz"),
    c("expiresAt", "expires_at", "timestamptz"),
    ...source("Entitlement"),
    c("entitlementMetadata", "entitlement_metadata", "jsonb"),
    created,
    updated,
    c("checkoutSessionRef", "checkout_session_ref", "text"),
    c("providerSubscriptionStatus", "provider_subscription_status", "text"),
    c("billingPeriodStartAt", "billing_period_start_at", "timestamptz"),
    c("billingPeriodEndAt", "billing_period_end_at", "timestamptz"),
    c("cancelAtPeriodEnd", "cancel_at_period_end", "boolean"),
    c("billingAmountMinor", "billing_amount_minor", "integer"),
    c("billingCurrency", "billing_currency", "text"),
    c("activeRoomCount", "active_room_count", "integer"),
    c("lastProviderEventCreatedAt", "last_provider_event_created_at", "timestamptz"),
    c("lastProviderEventId", "last_provider_event_id", "text"),
  ]),
};
