/** optional: written only when the planned rows carry the key, so other runs' SQL is unchanged. */
export type PmsColumn = readonly [jsonKey: string, sqlName: string, type: string, optional?: true];
export type PmsTableDefinition = {
  product: "pms" | "platform";
  table: string;
  key: readonly string[];
  freshness: string;
  mutable: boolean;
  columns: readonly PmsColumn[];
};

const c = (jsonKey: string, sqlName: string, type: string): PmsColumn => [jsonKey, sqlName, type];
const id = c("id", "id", "uuid");
const property = c("propertyId", "property_id", "uuid");
const created = c("createdAt", "created_at", "timestamptz");
const updated = c("updatedAt", "updated_at", "timestamptz");

export const PRODUCTION_PMS_WRITE_ORDER = [
  "linked_inventory_groups",
  "room_types",
  "room_type_media",
  "rooms",
  "rate_plans",
  "rate_rules",
  "property_pricing_settings",
  "idempotency_keys",
  "domain_events",
  "outbox_events",
  "operating_calendar_revisions",
  "operating_calendar_recurring_periods",
  "operating_calendar_room_bindings",
  "operational_booking_assignments",
  "room_blocks",
  "inventory_days",
  "checkin_checklist_templates",
  "checkout_inspection_templates",
  "calendar_auto_open_settings",
  "booking_checkin_records",
  "booking_checkout_charges",
  "booking_checkout_records",
  "booking_notes_private",
  "message_threads",
  "messages",
  "message_attachments",
  "channel_binding_claims",
  "channel_connections",
  "channel_room_type_mappings",
  "channel_rate_plan_mappings",
  "channel_booking_mappings",
  "channel_sync_status",
  "external_webhook_events",
  "product_audit_events",
] as const;

export const PRODUCTION_PMS_TABLES: Record<string, PmsTableDefinition> = {
  linked_inventory_groups: table("pms.linked_inventory_groups", true, [
    id,
    property,
    c("name", "name", "text"),
    c("revision", "revision", "integer"),
    created,
    updated,
  ]),
  room_types: table("pms.room_types", true, [
    id,
    property,
    c("sourceSystem", "source_system", "text"),
    c("sourceRoomTypeId", "source_room_type_id", "text"),
    c("name", "name", "text"),
    c("description", "description", "text"),
    c("category", "category", "text"),
    c("occupancyLimits", "occupancy_limits", "jsonb"),
    c("roomAttributes", "room_attributes", "jsonb"),
    c("amenitiesSnapshot", "amenities_snapshot", "jsonb"),
    c("mediaSnapshot", "media_snapshot", "jsonb"),
    c("baseRateAmount", "base_rate_amount", "numeric"),
    c("currency", "currency", "text"),
    c("active", "active", "boolean"),
    c("sortOrder", "sort_order", "integer"),
    c("locationSummary", "location_summary", "jsonb"),
    c("linkedInventoryGroupId", "linked_inventory_group_id", "uuid"),
    created,
    updated,
  ]),
  room_type_media: {
    ...table("pms.room_type_media", true, [
      property,
      c("roomTypeId", "room_type_id", "uuid"),
      c("platformMediaObjectId", "platform_media_object_id", "uuid"),
      c("altText", "alt_text", "text"),
      c("sortOrder", "sort_order", "integer"),
      created,
      updated,
    ]),
    key: ["room_type_id", "platform_media_object_id"],
  },
  rooms: table("pms.rooms", true, [
    id,
    property,
    c("roomTypeId", "room_type_id", "uuid"),
    c("sourceSystem", "source_system", "text"),
    c("sourceRoomId", "source_room_id", "text"),
    c("roomNumber", "room_number", "text"),
    // Stated by cohort runs only (VAY-1362); other runs leave the column to its 0048 default.
    ["operationalLabelStatus", "operational_label_status", "text", true],
    c("floor", "floor", "text"),
    c("status", "status", "text"),
    c("sortOrder", "sort_order", "integer"),
    c("roomMetadata", "room_metadata", "jsonb"),
    created,
    updated,
  ]),
  rate_plans: table("pms.rate_plans", true, [
    id,
    property,
    c("roomTypeId", "room_type_id", "uuid"),
    c("code", "code", "text"),
    c("name", "name", "text"),
    c("rateType", "rate_type", "text"),
    c("mealPlan", "meal_plan", "text"),
    c("paymentPolicy", "payment_policy", "jsonb"),
    c("depositPolicy", "deposit_policy", "jsonb"),
    c("cancellationPolicySnapshot", "cancellation_policy_snapshot", "jsonb"),
    c("baseRateAmount", "base_rate_amount", "numeric"),
    c("currency", "currency", "text"),
    c("active", "active", "boolean"),
    created,
    updated,
  ]),
  rate_rules: table("pms.rate_rules", true, [
    id,
    property,
    c("roomTypeId", "room_type_id", "uuid"),
    c("ratePlanId", "rate_plan_id", "uuid"),
    c("ruleType", "rule_type", "text"),
    c("startsOn", "starts_on", "date"),
    c("endsOn", "ends_on", "date"),
    c("daysOfWeek", "days_of_week", "integer[]"),
    c("minStayNights", "min_stay_nights", "integer"),
    c("maxStayNights", "max_stay_nights", "integer"),
    c("closedToArrival", "closed_to_arrival", "boolean"),
    c("closedToDeparture", "closed_to_departure", "boolean"),
    c("priceDeltaAmount", "price_delta_amount", "numeric"),
    c("priceDeltaPercent", "price_delta_percent", "numeric"),
    c("rulePayload", "rule_payload", "jsonb"),
    created,
    updated,
  ]),
  // optional_pricing_aggregate_revision keeps its default 0, as the native first-currency insert.
  property_pricing_settings: {
    ...table("pms.property_pricing_settings", true, [
      property,
      c("currency", "currency", "text"),
      c("pricingCurrencyRevision", "pricing_currency_revision", "integer"),
      created,
      updated,
    ]),
    key: ["property_id"],
  },
  // VAY-1362 cohort operating calendar: the revision, its bindings and the platform rows its
  // foreign keys require. Consumer-owned columns (statuses, leases, attempts) are not compared.
  idempotency_keys: platformTable("platform.idempotency_keys", "completed_at", [
    id,
    c("operationScope", "operation_scope", "text"),
    c("operation", "operation", "text"),
    c("keyHash", "key_hash", "text"),
    c("requestFingerprintHash", "request_fingerprint_hash", "text"),
    c("status", "status", "text"),
    c("tenantScope", "tenant_scope", "text"),
    c("organizationId", "organization_id", "uuid"),
    property,
    c("responseStatusCode", "response_status_code", "integer"),
    c("responseBodyHash", "response_body_hash", "text"),
    c("correlationId", "correlation_id", "text"),
    c("firstSeenAt", "first_seen_at", "timestamptz"),
    c("lastSeenAt", "last_seen_at", "timestamptz"),
    c("completedAt", "completed_at", "timestamptz"),
    c("expiresAt", "expires_at", "timestamptz"),
    c("idempotencyMetadata", "idempotency_metadata", "jsonb"),
  ]),
  domain_events: platformTable("platform.domain_events", "occurred_at", [
    id,
    c("sourceSystem", "source_system", "text"),
    c("eventKey", "event_key", "text"),
    c("eventType", "event_type", "text"),
    c("eventVersion", "event_version", "integer"),
    c("occurredAt", "occurred_at", "timestamptz"),
    c("tenantScope", "tenant_scope", "text"),
    c("organizationId", "organization_id", "uuid"),
    property,
    c("resourceProduct", "resource_product", "text"),
    c("resourceType", "resource_type", "text"),
    c("resourceId", "resource_id", "text"),
    c("actorType", "actor_type", "text"),
    c("actorUserId", "actor_user_id", "uuid"),
    c("correlationId", "correlation_id", "text"),
    c("causationId", "causation_id", "text"),
    c("idempotencyKeyHash", "idempotency_key_hash", "text"),
    c("payload", "payload", "jsonb"),
    c("eventMetadata", "event_metadata", "jsonb"),
    c("privacyScope", "privacy_scope", "text"),
  ]),
  outbox_events: platformTable("platform.outbox_events", "created_at", [
    id,
    c("domainEventId", "domain_event_id", "uuid"),
    c("outboxKey", "outbox_key", "text"),
    c("destination", "destination", "text"),
    c("eventType", "event_type", "text"),
    c("tenantScope", "tenant_scope", "text"),
    c("organizationId", "organization_id", "uuid"),
    property,
    c("resourceProduct", "resource_product", "text"),
    c("resourceType", "resource_type", "text"),
    c("resourceId", "resource_id", "text"),
    c("correlationId", "correlation_id", "text"),
    c("idempotencyKeyHash", "idempotency_key_hash", "text"),
    c("payload", "payload", "jsonb"),
    c("outboxMetadata", "outbox_metadata", "jsonb"),
    created,
  ]),
  operating_calendar_revisions: {
    ...table("pms.operating_calendar_revisions", false, [
      c("organizationId", "organization_id", "uuid"),
      property,
      c("calendarRevision", "calendar_revision", "integer"),
      c("contractVersion", "contract_version", "text"),
      c("propertyProfileRevision", "property_profile_revision", "integer"),
      c("propertyTimeZone", "property_time_zone", "text"),
      c("scheduleMode", "schedule_mode", "text"),
      c("recurringPeriodCount", "recurring_period_count", "smallint"),
      c("roomBindingCount", "room_binding_count", "integer"),
      c("defaultMinimumStayNights", "default_minimum_stay_nights", "smallint"),
      c("idempotencyKeyId", "idempotency_key_id", "uuid"),
      c("domainEventId", "domain_event_id", "uuid"),
      c("outboxEventId", "outbox_event_id", "uuid"),
      c("createdByUserId", "created_by_user_id", "uuid"),
      created,
      updated,
    ]),
    key: ["property_id", "calendar_revision"],
  },
  operating_calendar_recurring_periods: {
    ...table(
      "pms.operating_calendar_recurring_periods",
      false,
      [
        property,
        c("calendarRevision", "calendar_revision", "integer"),
        c("periodIndex", "period_index", "smallint"),
        c("startMonth", "start_month", "smallint"),
        c("startDay", "start_day", "smallint"),
        c("endMonth", "end_month", "smallint"),
        c("endDay", "end_day", "smallint"),
      ],
      "NULL",
    ),
    key: ["property_id", "calendar_revision", "period_index"],
  },
  operating_calendar_room_bindings: {
    ...table(
      "pms.operating_calendar_room_bindings",
      false,
      [
        property,
        c("calendarRevision", "calendar_revision", "integer"),
        c("roomTypeId", "room_type_id", "uuid"),
        c("sourceRoomFactsRevision", "source_room_facts_revision", "integer"),
        c("sourceRoomUnitsRevision", "source_room_units_revision", "integer"),
        c("physicalCapacityCount", "physical_capacity_count", "smallint"),
        c("startingSellableLimitCount", "starting_sellable_limit_count", "smallint"),
      ],
      "NULL",
    ),
    key: ["property_id", "calendar_revision", "room_type_id"],
  },
  operational_booking_assignments: table("pms.operational_booking_assignments", true, [
    id,
    property,
    c("guestBookingId", "guest_booking_id", "uuid"),
    c("roomTypeId", "room_type_id", "uuid"),
    c("ratePlanId", "rate_plan_id", "uuid"),
    c("roomId", "room_id", "uuid"),
    c("position", "position", "integer"),
    c("assignmentStatus", "assignment_status", "text"),
    c("pmsReservationRef", "pms_reservation_ref", "text"),
    c("externalReservationId", "external_reservation_id", "text"),
    c("channel", "channel", "text"),
    c("source", "source", "text"),
    c("assignmentPayload", "assignment_payload", "jsonb"),
    c("assignedAt", "assigned_at", "timestamptz"),
    created,
    updated,
    c("stayEvidenceKind", "stay_evidence_kind", "text"),
    c("checkIn", "check_in", "date"),
    c("checkOut", "check_out", "date"),
    c("adults", "adults", "integer"),
    c("children", "children", "integer"),
  ]),
  room_blocks: table("pms.room_blocks", true, [
    id,
    property,
    c("roomTypeId", "room_type_id", "uuid"),
    c("roomId", "room_id", "uuid"),
    c("startsOn", "starts_on", "date"),
    c("endsOn", "ends_on", "date"),
    c("blockedCount", "blocked_count", "integer"),
    c("reason", "reason", "text"),
    c("status", "status", "text"),
    c("createdByUserId", "created_by_user_id", "uuid"),
    created,
    c("releasedAt", "released_at", "timestamptz"),
    c("revision", "revision", "integer"),
    updated,
    c("blockKind", "block_kind", "text"),
    c("sourceRoomTypeId", "source_room_type_id", "uuid"),
    c("sourceInventoryReservationReceiptId", "source_inventory_reservation_receipt_id", "uuid"),
    c("sourceAssignmentId", "source_assignment_id", "uuid"),
    c("sourceRoomBlockId", "source_room_block_id", "uuid"),
  ]),
  inventory_days: {
    ...table("pms.inventory_days", true, [
      property,
      c("roomTypeId", "room_type_id", "uuid"),
      c("stayDate", "stay_date", "date"),
      c("totalCount", "total_count", "integer"),
      c("assignedCount", "assigned_count", "integer"),
      c("blockedCount", "blocked_count", "integer"),
      c("availableCount", "available_count", "integer"),
      c("status", "status", "text"),
      c("sourceFreshness", "source_freshness", "jsonb"),
      updated,
      c("calendarRevision", "calendar_revision", "integer"),
      c("inventoryRevision", "inventory_revision", "integer"),
      c("generatedSellableLimitCount", "generated_sellable_limit_count", "integer"),
      c("channelSellableLimitCount", "channel_sellable_limit_count", "integer"),
      c("manualSellableLimitCount", "manual_sellable_limit_count", "integer"),
      c("effectiveSellableLimitCount", "effective_sellable_limit_count", "integer"),
      c("generatedSourceRevision", "generated_source_revision", "integer"),
      c("channelSourceRevision", "channel_source_revision", "integer"),
      c("manualSourceRevision", "manual_source_revision", "integer"),
      c("blockSourceRevision", "block_source_revision", "integer"),
      c("bookingSourceRevision", "booking_source_revision", "integer"),
      c("linkedStopSell", "linked_stop_sell", "boolean"),
      c("linkedSourceRevision", "linked_source_revision", "integer"),
    ]),
    key: ["property_id", "room_type_id", "stay_date"],
  },
  checkin_checklist_templates: propertyTable("pms.checkin_checklist_templates"),
  checkout_inspection_templates: propertyTable("pms.checkout_inspection_templates"),
  calendar_auto_open_settings: {
    ...table("pms.calendar_auto_open_settings", true, [
      property,
      c("revision", "revision", "integer"),
      c("enabled", "enabled", "boolean"),
      c("mode", "mode", "text"),
      c("rollingMonths", "rolling_months", "smallint"),
      c("fixedEndMonth", "fixed_end_month", "date"),
      updated,
    ]),
    key: ["property_id"],
  },
  booking_checkin_records: table(
    "pms.booking_checkin_records",
    false,
    [
      id,
      property,
      c("guestBookingId", "guest_booking_id", "uuid"),
      c("assignmentId", "assignment_id", "uuid"),
      c("completedByUserId", "completed_by_user_id", "uuid"),
      c("completedAt", "completed_at", "timestamptz"),
      c("stepResults", "step_results", "jsonb"),
      c("pendingFlags", "pending_flags", "jsonb"),
    ],
    "completed_at",
  ),
  booking_checkout_charges: table(
    "pms.booking_checkout_charges",
    true,
    [
      id,
      property,
      c("guestBookingId", "guest_booking_id", "uuid"),
      c("assignmentId", "assignment_id", "uuid"),
      c("label", "label", "text"),
      c("amount", "amount", "numeric"),
      c("originalAmount", "original_amount", "numeric"),
      c("currency", "currency", "text"),
      c("status", "status", "text"),
      c("createdByUserId", "created_by_user_id", "uuid"),
      created,
      c("settledAt", "settled_at", "timestamptz"),
      c("waivedAt", "waived_at", "timestamptz"),
    ],
    "COALESCE(waived_at, settled_at, created_at)",
  ),
  booking_checkout_records: table(
    "pms.booking_checkout_records",
    false,
    [
      id,
      property,
      c("guestBookingId", "guest_booking_id", "uuid"),
      c("assignmentId", "assignment_id", "uuid"),
      c("completedByUserId", "completed_by_user_id", "uuid"),
      c("completedAt", "completed_at", "timestamptz"),
      c("inspectionResults", "inspection_results", "jsonb"),
      c("chargesSettled", "charges_settled", "jsonb"),
      c("pendingFlags", "pending_flags", "jsonb"),
      c("checkoutNotes", "checkout_notes", "text"),
    ],
    "completed_at",
  ),
  booking_notes_private: table(
    "pms.booking_notes_private",
    true,
    [
      id,
      property,
      c("guestBookingId", "guest_booking_id", "uuid"),
      c("authorUserId", "author_user_id", "uuid"),
      c("authorDisplayName", "author_display_name", "text"),
      c("body", "body", "text"),
      c("source", "source", "text"),
      created,
      c("editedByUserId", "edited_by_user_id", "uuid"),
      c("editedByDisplayName", "edited_by_display_name", "text"),
      c("editedAt", "edited_at", "timestamptz"),
    ],
    "COALESCE(edited_at, created_at)",
  ),
  message_threads: table("pms.message_threads", true, [
    id,
    property,
    c("guestBookingId", "guest_booking_id", "uuid"),
    c("source", "source", "text"),
    c("sourceThreadId", "source_thread_id", "text"),
    c("sourceBookingId", "source_booking_id", "text"),
    c("providerChannel", "provider_channel", "text"),
    c("deliveryChannel", "delivery_channel", "text"),
    c("guestDisplayName", "guest_display_name", "text"),
    c("guestEmail", "guest_email", "text"),
    c("attentionState", "attention_state", "text"),
    c("doneAt", "done_at", "timestamptz"),
    c("doneReason", "done_reason", "text"),
    c("conversationContextState", "conversation_context_state", "text"),
    c("inquiryArrivalDate", "inquiry_arrival_date", "date"),
    c("inquiryDepartureDate", "inquiry_departure_date", "date"),
    c("inquiryAdults", "inquiry_adults", "integer"),
    c("inquiryChildren", "inquiry_children", "integer"),
    c("lastMessageAt", "last_message_at", "timestamptz"),
    c("lastMessagePreview", "last_message_preview", "text"),
    c("lastMessageDirection", "last_message_direction", "text"),
    c("unreadCount", "unread_count", "integer"),
    created,
    updated,
  ]),
  messages: table(
    "pms.messages",
    true,
    [
      id,
      property,
      c("threadId", "thread_id", "uuid"),
      c("sourceMessageId", "source_message_id", "text"),
      c("direction", "direction", "text"),
      c("senderType", "sender_type", "text"),
      c("senderUserId", "sender_user_id", "uuid"),
      c("senderDisplayName", "sender_display_name", "text"),
      c("body", "body", "text"),
      c("sentAt", "sent_at", "timestamptz"),
      c("receivedAt", "received_at", "timestamptz"),
      c("readAt", "read_at", "timestamptz"),
      c("rawPayload", "raw_payload", "jsonb"),
      c("piiRetentionUntil", "pii_retention_until", "date"),
    ],
    "COALESCE(read_at, received_at)",
  ),
  message_attachments: table(
    "pms.message_attachments",
    false,
    [
      id,
      property,
      c("messageId", "message_id", "uuid"),
      c("platformMediaObjectId", "platform_media_object_id", "uuid"),
      c("s3Key", "s3_key", "text"),
      c("sourceUrl", "source_url", "text"),
      c("filename", "filename", "text"),
      c("contentType", "content_type", "text"),
      c("sizeBytes", "size_bytes", "integer"),
      c("sourceAttachmentId", "source_attachment_id", "text"),
      created,
    ],
    "created_at",
  ),
  channel_binding_claims: {
    product: "pms",
    table: "pms.channel_binding_claims",
    key: ["property_id", "provider"],
    freshness: "updated_at",
    mutable: false,
    columns: [
      property,
      c("provider", "provider", "text"),
      c("externalPropertyId", "external_property_id", "text"),
      c("claimState", "claim_state", "text"),
      c("claimSource", "claim_source", "text"),
      created,
      updated,
    ],
  },
  channel_connections: table("pms.channel_connections", true, [
    id,
    property,
    c("provider", "provider", "text"),
    c("connectionStatus", "connection_status", "text"),
    c("externalPropertyId", "external_property_id", "text"),
    c("capabilities", "capabilities", "text[]"),
    c("messagingAppInstalled", "messaging_app_installed", "boolean"),
    c("lastBookingSyncAt", "last_booking_sync_at", "timestamptz"),
    c("lastAriSyncAt", "last_ari_sync_at", "timestamptz"),
    c("lastMessageSyncAt", "last_message_sync_at", "timestamptz"),
    c("connectionMetadata", "connection_metadata", "jsonb"),
    created,
    updated,
  ]),
  channel_room_type_mappings: table(
    "pms.channel_room_type_mappings",
    true,
    mappingColumns([
      c("roomTypeId", "room_type_id", "uuid"),
      c("externalRoomTypeId", "external_room_type_id", "text"),
      c("status", "status", "text"),
      c("mappingMetadata", "mapping_metadata", "jsonb"),
    ]),
  ),
  channel_rate_plan_mappings: table(
    "pms.channel_rate_plan_mappings",
    true,
    mappingColumns([
      c("roomTypeId", "room_type_id", "uuid"),
      c("ratePlanId", "rate_plan_id", "uuid"),
      c("channel", "channel", "text"),
      c("externalRoomTypeId", "external_room_type_id", "text"),
      c("externalRatePlanId", "external_rate_plan_id", "text"),
      c("sellMode", "sell_mode", "text"),
      c("markupPercent", "markup_percent", "numeric"),
      c("status", "status", "text"),
      c("mappingMetadata", "mapping_metadata", "jsonb"),
    ]),
  ),
  channel_booking_mappings: table(
    "pms.channel_booking_mappings",
    true,
    mappingColumns([
      c("guestBookingId", "guest_booking_id", "uuid"),
      c("assignmentId", "assignment_id", "uuid"),
      c("externalBookingId", "external_booking_id", "text"),
      c("externalRevisionId", "external_revision_id", "text"),
      c("channel", "channel", "text"),
      c("channelRoomIndex", "channel_room_index", "integer"),
      c("syncStatus", "sync_status", "text"),
      c("lastSyncedAt", "last_synced_at", "timestamptz"),
      c("mappingMetadata", "mapping_metadata", "jsonb"),
    ]),
  ),
  channel_sync_status: table("pms.channel_sync_status", true, [
    id,
    property,
    c("connectionId", "connection_id", "uuid"),
    c("syncDomain", "sync_domain", "text"),
    c("status", "status", "text"),
    c("lastAttemptAt", "last_attempt_at", "timestamptz"),
    c("lastSuccessAt", "last_success_at", "timestamptz"),
    c("lastErrorCode", "last_error_code", "text"),
    c("lastErrorMessage", "last_error_message", "text"),
    c("retryAfter", "retry_after", "timestamptz"),
    c("syncPayload", "sync_payload", "jsonb"),
    updated,
  ]),
  external_webhook_events: platformTable("platform.external_webhook_events", "received_at", [
    id,
    c("provider", "provider", "text"),
    c("providerEventId", "provider_event_id", "text"),
    c("webhookKeyHash", "webhook_key_hash", "text"),
    c("eventType", "event_type", "text"),
    c("deliveryStatus", "delivery_status", "text"),
    c("signatureVerified", "signature_verified", "boolean"),
    c("receivedAt", "received_at", "timestamptz"),
    c("processedAt", "processed_at", "timestamptz"),
    c("tenantScope", "tenant_scope", "text"),
    c("organizationId", "organization_id", "uuid"),
    property,
    c("normalizedDomainEventId", "normalized_domain_event_id", "uuid"),
    c("correlationId", "correlation_id", "text"),
    c("payloadHash", "payload_hash", "text"),
    c("rawHeaders", "raw_headers", "jsonb"),
    c("rawPayload", "raw_payload", "jsonb"),
    c("payloadRetentionUntil", "payload_retention_until", "timestamptz"),
    c("failureReason", "failure_reason", "text"),
    c("privacyScope", "privacy_scope", "text"),
    c("aiVisible", "ai_visible", "boolean"),
  ]),
  product_audit_events: platformTable("platform.product_audit_events", "occurred_at", [
    id,
    c("auditKey", "audit_key", "text"),
    c("product", "product", "text"),
    c("action", "action", "text"),
    c("actionVersion", "action_version", "integer"),
    c("occurredAt", "occurred_at", "timestamptz"),
    c("recordedAt", "recorded_at", "timestamptz"),
    c("tenantScope", "tenant_scope", "text"),
    c("organizationId", "organization_id", "uuid"),
    property,
    c("actorType", "actor_type", "text"),
    c("actorUserId", "actor_user_id", "uuid"),
    c("targetResourceProduct", "target_resource_product", "text"),
    c("targetResourceType", "target_resource_type", "text"),
    c("targetResourceId", "target_resource_id", "text"),
    c("secondaryResourceProduct", "secondary_resource_product", "text"),
    c("secondaryResourceType", "secondary_resource_type", "text"),
    c("secondaryResourceId", "secondary_resource_id", "text"),
    c("domainEventId", "domain_event_id", "uuid"),
    c("externalWebhookEventId", "external_webhook_event_id", "uuid"),
    c("jobId", "job_id", "uuid"),
    c("idempotencyKeyId", "idempotency_key_id", "uuid"),
    c("correlationId", "correlation_id", "text"),
    c("causationId", "causation_id", "text"),
    c("redactedPayload", "redacted_payload", "jsonb"),
    c("privatePayload", "private_payload", "jsonb"),
    c("auditMetadata", "audit_metadata", "jsonb"),
    c("retentionClass", "retention_class", "text"),
    c("privacyScope", "privacy_scope", "text"),
    c("aiVisible", "ai_visible", "boolean"),
  ]),
};

function table(
  name: string,
  mutable: boolean,
  columns: readonly PmsColumn[],
  freshness = "updated_at",
): PmsTableDefinition {
  return { product: "pms", table: name, key: ["id"], freshness, mutable, columns };
}

function propertyTable(name: string): PmsTableDefinition {
  return {
    ...table(name, true, [
      property,
      c("steps", "steps", "jsonb"),
      c("updatedByUserId", "updated_by_user_id", "uuid"),
      updated,
    ]),
    key: ["property_id"],
  };
}

function mappingColumns(values: readonly PmsColumn[]): readonly PmsColumn[] {
  return [id, property, c("connectionId", "connection_id", "uuid"), ...values, created, updated];
}

function platformTable(
  name: string,
  freshness: string,
  columns: readonly PmsColumn[],
): PmsTableDefinition {
  return { product: "platform", table: name, key: ["id"], freshness, mutable: false, columns };
}
