import type pg from "pg";

type ProjectionStep = {
  target: string;
  source: string;
  targetColumns: string[];
  selectExpressions: string[];
  onConflict?: string;
};

function sourceTable(name: string): string {
  return `migration_source_intelligence.${name}`;
}

const projectionSteps: ProjectionStep[] = [
  {
    target: "identity.users",
    source: sourceTable("owner_accounts"),
    targetColumns: ["id", "email", "name", "status"],
    selectExpressions: ["owner_user_id", "owner_email", "owner_name", "owner_status"],
  },
  {
    target: "identity.organizations",
    source: sourceTable("owner_organizations"),
    targetColumns: ["id", "kind", "name", "slug", "status", "workos_org_id", "workos_external_id"],
    selectExpressions: [
      "org_id",
      "org_kind",
      "org_name",
      "org_slug",
      "org_status",
      "workos_org_id",
      "workos_external_id",
    ],
  },
  {
    target: "identity.organization_memberships",
    source: sourceTable("owner_memberships"),
    targetColumns: [
      "id",
      "organization_id",
      "user_id",
      "status",
      "role_key",
      "workos_membership_id",
      "workos_role_slugs",
    ],
    selectExpressions: [
      "membership_id",
      "org_id",
      "owner_user_id",
      "membership_status",
      "role_key",
      "workos_membership_id",
      "workos_role_slugs",
    ],
  },
  {
    target: "identity.role_permission_grants",
    source: sourceTable("role_permission_inputs"),
    targetColumns: ["organization_kind", "role_key", "permission_key"],
    selectExpressions: ["org_kind", "role_key", "permission_key"],
    onConflict: "ON CONFLICT (organization_kind, role_key, permission_key) DO NOTHING",
  },
  {
    target: "identity.organization_resource_links",
    source: sourceTable("organization_resource_inputs"),
    targetColumns: [
      "id",
      "organization_id",
      "product",
      "resource_type",
      "resource_id",
      "relationship",
      "status",
    ],
    selectExpressions: [
      "link_id",
      "org_id",
      "product",
      "resource_type",
      "source_resource_id",
      "relationship",
      "link_status",
    ],
  },
  {
    target: "identity.product_entitlements",
    source: sourceTable("product_entitlement_inputs"),
    targetColumns: [
      "id",
      "organization_id",
      "product",
      "entitlement_key",
      "status",
      "resource_product",
      "resource_type",
      "resource_id",
      "starts_at",
      "metadata",
    ],
    selectExpressions: [
      "entitlement_id",
      "org_id",
      "product",
      "entitlement_key",
      "entitlement_status",
      "resource_product",
      "resource_type",
      "source_resource_id",
      "starts_at",
      "source_metadata",
    ],
  },
  {
    target: "hotel_catalog.properties",
    source: sourceTable("property_profile_inputs"),
    targetColumns: [
      "id",
      "public_id",
      "display_name",
      "property_type",
      "category",
      "default_locale",
      "supported_locales",
      "profile_status",
      "completeness_reasons",
    ],
    selectExpressions: [
      "property_id",
      "property_public_id",
      "property_display_name",
      "property_type",
      "property_category",
      "default_locale",
      "supported_locales",
      "profile_status",
      "completeness_reasons",
    ],
  },
  {
    target: "hotel_catalog.property_source_links",
    source: sourceTable("property_source_inputs"),
    targetColumns: [
      "id",
      "property_id",
      "source_system",
      "source_table",
      "source_id",
      "relationship",
      "metadata",
    ],
    selectExpressions: [
      "source_link_id",
      "property_id",
      "source_system",
      "source_table",
      "source_id",
      "relationship",
      "source_metadata",
    ],
  },
  {
    target: "intelligence.metric_definitions",
    source: sourceTable("metric_catalog_inputs"),
    targetColumns: [
      "id",
      "metric_key",
      "display_name",
      "description",
      "product",
      "metric_category",
      "unit",
      "default_resource_scope",
      "required_permission_key",
      "visibility",
      "freshness_slo_seconds",
      "pii_policy",
      "allowed_filters",
      "definition_metadata",
      "active",
      "created_at",
      "updated_at",
    ],
    selectExpressions: [
      "metric_id",
      "metric_key",
      "label",
      "metric_description",
      "product",
      "category",
      "unit",
      "resource_scope",
      "permission_key",
      "visibility",
      "freshness_slo_seconds",
      "pii_policy",
      "allowed_filters",
      "metadata",
      "active",
      "created_at",
      "updated_at",
    ],
  },
  {
    target: "intelligence.metric_snapshot_runs",
    source: sourceTable("metric_snapshot_inputs"),
    targetColumns: [
      "id",
      "metric_definition_id",
      "metric_key",
      "snapshot_key",
      "run_status",
      "resource_scope",
      "organization_id",
      "property_id",
      "source_owner",
      "source_view",
      "required_permission_key",
      "snapshot_period",
      "period_start",
      "period_end",
      "generated_at",
      "source_fresh_at",
      "expires_at",
      "freshness_status",
      "quality",
      "sample_size",
      "aggregate_id",
      "value_summary",
      "filters",
      "source_freshness",
      "unavailable_reasons",
      "snapshot_metadata",
      "created_at",
    ],
    selectExpressions: [
      "snapshot_run_id",
      "metric_id",
      "metric_key",
      "snapshot_key",
      "status",
      "resource_scope",
      "org_id",
      "property_id",
      "source_owner",
      "source_view",
      "permission_key",
      "period",
      "period_start",
      "period_end",
      "generated_at",
      "source_fresh_at",
      "expires_at",
      "freshness_status",
      "quality",
      "sample_size",
      "aggregate_id",
      "value_summary",
      "filters",
      "source_freshness",
      "unavailable_reasons",
      "metadata",
      "created_at",
    ],
  },
  {
    target: "intelligence.setup_completeness_snapshots",
    source: sourceTable("setup_snapshot_inputs"),
    targetColumns: [
      "id",
      "snapshot_key",
      "organization_id",
      "property_id",
      "setup_area",
      "completion_status",
      "completeness_score",
      "required_permission_key",
      "source_snapshot_at",
      "source_fresh_at",
      "freshness_status",
      "missing_items",
      "blocking_items",
      "stale_items",
      "source_freshness",
      "setup_metadata",
      "created_at",
    ],
    selectExpressions: [
      "setup_snapshot_id",
      "snapshot_key",
      "org_id",
      "property_id",
      "setup_area",
      "status",
      "completeness_score",
      "permission_key",
      "source_snapshot_at",
      "source_fresh_at",
      "freshness_status",
      "missing_items",
      "blocking_items",
      "stale_items",
      "source_freshness",
      "metadata",
      "created_at",
    ],
  },
  {
    target: "intelligence.ai_evidence_catalog",
    source: sourceTable("evidence_tool_inputs"),
    targetColumns: [
      "id",
      "tool_id",
      "tool_version",
      "display_name",
      "product",
      "source_owner",
      "source_view",
      "primary_metric_definition_id",
      "read_only",
      "required_resource_scope",
      "primary_required_permission_key",
      "required_permission_keys",
      "supported_intents",
      "allowed_filters",
      "freshness_slo_seconds",
      "pii_policy",
      "unavailable_reasons",
      "evidence_contract",
      "status",
      "created_at",
      "updated_at",
    ],
    selectExpressions: [
      "evidence_tool_id",
      "tool_id",
      "tool_version",
      "label",
      "product",
      "source_owner",
      "source_view",
      "metric_id",
      "read_only",
      "resource_scope",
      "permission_key",
      "permission_keys",
      "supported_intents",
      "allowed_filters",
      "freshness_slo_seconds",
      "pii_policy",
      "unavailable_reasons",
      "contract",
      "status",
      "created_at",
      "updated_at",
    ],
  },
  {
    target: "intelligence.ask_conversations",
    source: sourceTable("ask_conversation_inputs"),
    targetColumns: [
      "id",
      "conversation_key",
      "actor_user_id",
      "organization_id",
      "property_id",
      "resource_scope",
      "conversation_state",
      "locale",
      "title",
      "retention_policy",
      "last_message_at",
      "privacy_scope",
      "conversation_metadata",
      "created_at",
      "updated_at",
    ],
    selectExpressions: [
      "conversation_id",
      "conversation_key",
      "actor_user_id",
      "org_id",
      "property_id",
      "resource_scope",
      "state",
      "locale",
      "title",
      "retention_policy",
      "last_message_at",
      "privacy_scope",
      "metadata",
      "created_at",
      "updated_at",
    ],
  },
  {
    target: "intelligence.ask_runs",
    source: sourceTable("ask_run_inputs"),
    targetColumns: [
      "id",
      "run_key",
      "conversation_id",
      "actor_user_id",
      "organization_id",
      "property_id",
      "resource_scope",
      "request_id",
      "correlation_id",
      "question_redacted_text",
      "question_hash",
      "detected_intent",
      "required_permission_key",
      "run_status",
      "confidence_level",
      "model_provider",
      "model_name",
      "prompt_version",
      "schema_version",
      "tool_plan",
      "unavailable_data",
      "caveats",
      "token_usage",
      "cost_metadata",
      "started_at",
      "finished_at",
      "latency_ms",
      "created_at",
    ],
    selectExpressions: [
      "run_id",
      "run_key",
      "conversation_id",
      "actor_user_id",
      "org_id",
      "property_id",
      "resource_scope",
      "request_id",
      "correlation_id",
      "question_text",
      "question_hash",
      "intent",
      "permission_key",
      "status",
      "confidence",
      "model_provider",
      "model_name",
      "prompt_version",
      "schema_version",
      "tool_plan",
      "unavailable_data",
      "caveats",
      "token_usage",
      "cost_metadata",
      "started_at",
      "finished_at",
      "latency_ms",
      "created_at",
    ],
  },
  {
    target: "intelligence.ask_tool_calls",
    source: sourceTable("ask_tool_call_inputs"),
    targetColumns: [
      "id",
      "run_id",
      "tool_id",
      "tool_version",
      "call_sequence",
      "resource_scope",
      "organization_id",
      "property_id",
      "required_permission_key",
      "authorization_status",
      "result_status",
      "input_scope",
      "filters",
      "evidence_references",
      "unavailable_data",
      "result_summary",
      "latency_ms",
      "started_at",
      "finished_at",
      "created_at",
    ],
    selectExpressions: [
      "tool_call_id",
      "run_id",
      "tool_id",
      "tool_version",
      "call_sequence",
      "resource_scope",
      "org_id",
      "property_id",
      "permission_key",
      "authorization_status",
      "result_status",
      "input_scope",
      "filters",
      "evidence_references",
      "unavailable_data",
      "result_summary",
      "latency_ms",
      "started_at",
      "finished_at",
      "created_at",
    ],
  },
  {
    target: "intelligence.ask_answer_audits",
    source: sourceTable("ask_answer_inputs"),
    targetColumns: [
      "id",
      "answer_id",
      "run_id",
      "conversation_id",
      "organization_id",
      "property_id",
      "resource_scope",
      "contract_version",
      "answer_status",
      "confidence_level",
      "question_hash",
      "audit_revision",
      "summary",
      "generated_answer",
      "evidence_references",
      "material_claims",
      "suggested_actions",
      "unavailable_data",
      "caveats",
      "review_status",
      "retention_class",
      "privacy_scope",
      "audit_metadata",
      "created_at",
    ],
    selectExpressions: [
      "audit_id",
      "answer_id",
      "run_id",
      "conversation_id",
      "org_id",
      "property_id",
      "resource_scope",
      "contract_version",
      "answer_status",
      "confidence",
      "question_hash",
      "audit_revision",
      "summary",
      "generated_answer",
      "evidence_references",
      "material_claims",
      "suggested_actions",
      "unavailable_data",
      "caveats",
      "review_status",
      "retention_class",
      "privacy_scope",
      "metadata",
      "created_at",
    ],
  },
];

export async function transformIntelligence(client: pg.Client): Promise<void> {
  for (const step of projectionSteps) {
    await client.query(`
      INSERT INTO ${step.target} (${step.targetColumns.join(", ")})
      SELECT ${step.selectExpressions.join(", ")}
      FROM ${step.source}
      ${step.onConflict ?? ""}
    `);
  }
}
