// prettier-ignore
import type { LinkedResource, PermissionKey, ProductEntitlement, RequestContext } from "@vayada/backend-auth";
import { buildApp } from "./app.js";
import { agencyPropertyAccessRepository } from "./testAuthorization.js";
import type { FinanceExpenseRoutesOptions } from "./routes/financeExpenses.js";
import { describe, expect, it, vi } from "vitest";

// prettier-ignore
const propertyId = "1214a000-0000-4000-8000-000000000001", otherProperty = "1214b000-0000-4000-8000-000000000002", categoryId = "1214c000-0000-4000-8000-000000000003", expenseId = "1214d000-0000-4000-8000-000000000004", ruleId = "1214e000-0000-4000-8000-000000000005";
// prettier-ignore
const root = `/api/finance/properties/${propertyId}/financials`, now = "2026-08-11T10:00:00.000Z";
// prettier-ignore
const base = { contractVersion: "pms-financials.v1", propertyId, currency: "EUR", timeZone: "Europe/Berlin", generatedAt: now, sourceFreshness: { finance: now }, incompleteEvidence: [] };
// prettier-ignore
const category = { id: categoryId, systemKey: null, name: "Operations", color: "#123456", sortOrder: 1, archived: false, revision: 1 };
// prettier-ignore
const expense = { id: expenseId, categoryId, origin: "manual", incurredOn: "2026-08-11", vendor: "Vendor", amount: { amount: "12.0000", currency: "EUR" }, paymentStatus: "unpaid", paidOn: null, recurringRuleId: null, sourceKey: null, reversesExpenseId: null, revision: 1 };
// prettier-ignore
const rule = { id: ruleId, categoryId, vendor: "Vendor", amount: { amount: "12.0000", currency: "EUR" }, paymentStatus: "unpaid", cadence: "monthly", startsOn: "2026-08-11", nextDueOn: "2026-08-11", endsOn: null, active: true, revision: 1 };
const receiptId = "1214f000-0000-4000-8000-000000000006";

// prettier-ignore
function ports() {
  const zero = { value: { amount: "0.0000", currency: "EUR" }, absoluteChange: { amount: "0.0000", currency: "EUR" }, percentChange: null };
  const read = { categories: vi.fn(async () => ({ ...base, item: [category] })), expense: vi.fn(async (_propertyId, id) => ({ ...base, item: { ...expense, id } })), expenses: vi.fn(async () => ({ ...base, summary: { totalMtd: zero, perOccupiedNight: zero, unpaidAmount: zero, unpaidCount: { value: 0, absoluteChange: 0, percentChange: null } }, categories: [], page: { items: [], nextCursor: null, limit: 50 } })), recurringRule: vi.fn(async (_propertyId, id) => ({ ...base, item: { ...rule, id } })) };
  const categories = { create: vi.fn(async (command) => ({ status: command.idempotencyKey === "replay" ? "replayed" : "created", category })), update: vi.fn(async () => ({ status: "updated", category })), archive: vi.fn(async () => ({ status: "updated", category })) };
  const expenses = { create: vi.fn(async (command) => ({ ok: true, outcome: command.idempotencyKey === "replay" ? "replayed" : "created", item: { ...expense, id: command.commandId } })), update: vi.fn(async () => ({ ok: true, outcome: "updated", item: expense })), archive: vi.fn(async (command) => ({ ok: true, outcome: "archived", item: { ...expense, id: command.commandId.toLowerCase() } })) };
  const recurring = { create: vi.fn(async (command) => ({ ok: true, outcome: command.idempotencyKey === "replay" ? "replayed" : "created", item: { ...rule, id: command.commandId } })), update: vi.fn(async () => ({ ok: true, outcome: "updated", item: rule })), disable: vi.fn(async () => ({ ok: true, outcome: "updated", item: { ...rule, active: false } })) };
  const receiptMedia = { read: { receipt: vi.fn(async () => ({ mediaId: receiptId, propertyId, resourceId: expenseId, purpose: "finance.expense.receipt", resourceProduct: "finance", resourceType: "expense", visibility: "private", lifecycleStatus: "active", bucketName: "test-media", storageKey: `private/finance/${receiptId}/receipt.webp`, originalFilename: "receipt.webp", contentType: "image/webp" })) }, signer: { signPrivateDownload: vi.fn(async () => "https://signed.example/receipt?expires=300") }, serving: { bucketName: "test-media", cdnBaseUrl: "https://cdn.example", cdnOriginHost: "origin.example", publicPathPrefix: "media", publicCacheControl: "public, max-age=31536000, immutable", privateDownloadTtlSeconds: 300, privateDownloadMaxTtlSeconds: 900 }, now: () => new Date(now) };
  return { read, categories, expenses, recurring, receiptMedia } as unknown as FinanceExpenseRoutesOptions;
}
// prettier-ignore
async function app(options: FinanceExpenseRoutesOptions, auth: RequestContext | null = context()) { const instance = buildApp({ logger: false, financeExpenses: { ...options, propertyAccessRepository: agencyPropertyAccessRepository } }); instance.decorateRequest("authContext", null); instance.addHook("onRequest", async (request) => { request.authContext = auth; }); return instance; }
// prettier-ignore
const command = { commandId: ruleId, idempotencyKey: "key-1", expectedRevision: 1 };
// prettier-ignore
const write = { commandId: expenseId, idempotencyKey: "key-1", incurredOn: "2026-08-11", vendor: "Vendor", categoryId, amount: { amount: "12.0000", currency: "EUR" }, paymentStatus: "unpaid" };

it("denies unassigned expenses, commands and private receipt signing", async () => {
  const auth = context();
  auth.membership.propertyAccess!.assignedPropertyIds = [];
  const options = ports(),
    instance = await app(options, auth);
  try {
    for (const [method, url, payload] of [
      ["GET", `${root}/expense-categories`],
      ["POST", `${root}/expenses`, write],
      ["GET", `${root}/expenses/${expenseId}/receipt`],
    ] as const) {
      const response = await instance.inject({ method, url, payload });
      expect(response.statusCode).toBe(403);
      expect(response.json()).toEqual({ code: "forbidden" });
    }
    expect(options.read.categories).not.toHaveBeenCalled();
    expect(options.expenses.create).not.toHaveBeenCalled();
    expect(options.receiptMedia!.read.receipt).not.toHaveBeenCalled();
    expect(options.receiptMedia!.signer.signPrivateDownload).not.toHaveBeenCalled();
  } finally {
    await instance.close();
  }
});

// prettier-ignore
describe("Financials expense routes", () => {
  it("registers documented routes and returns the conditional recurrence shape", async () => { const options = ports(), instance = await app(options); const categoryWrite = { commandId: expenseId, idempotencyKey: "key-1", name: "Operations", color: "#123456", sortOrder: 1 }; const cases = [["GET", `${root}/expense-categories`], ["POST", `${root}/expense-categories`, categoryWrite], ["PATCH", `${root}/expense-categories/${categoryId}`, { ...command, commandId: categoryId, name: "Updated" }], ["DELETE", `${root}/expense-categories/${categoryId}`, { ...command, commandId: categoryId }], ["GET", `${root}/expenses?from=2026-08-01&to=2026-08-31`], ["POST", `${root}/expenses`, { ...write, commandId: expenseId.toUpperCase(), categoryId: categoryId.toUpperCase(), receiptMediaId: receiptId.toUpperCase() }], ["GET", `${root}/expenses/${expenseId}`], ["PATCH", `${root}/expenses/${expenseId}`, { ...command, commandId: expenseId, vendor: "Updated" }], ["DELETE", `${root}/expenses/${expenseId}`, { ...command, commandId: expenseId }], ["GET", `${root}/recurring-expenses/${ruleId}`], ["PATCH", `${root}/recurring-expenses/${ruleId}`, { ...command, categoryId, vendor: "Vendor", amount: write.amount, notes: null, paymentStatus: "paid", cadence: "weekly", nextDueOn: "2026-08-18", endsOn: null }], ["DELETE", `${root}/recurring-expenses/${ruleId}`, command]] as const; for (const [method, url, payload] of cases) { const response = await instance.inject({ method, url, payload }); expect(response.statusCode).toBeLessThan(300); expect(response.json().contractVersion).toBe("pms-financials.v1"); } expect(options.expenses.create).toHaveBeenCalledWith(expect.objectContaining({ receiptMediaId: receiptId }));
    let response = await instance.inject({ method: "POST", url: `${root}/expenses`, payload: { ...write, commandId: ruleId.toUpperCase(), categoryId: categoryId.toUpperCase(), recurrence: { cadence: "monthly", startsOn: "2026-08-11" } } }); expect(response.statusCode).toBe(201); expect(response.json()).toEqual({ ...base, item: rule, outcome: "created" }); expect(options.expenses.create).toHaveBeenCalledOnce(); expect(options.recurring.create).toHaveBeenCalledOnce(); expect(options.recurring.create).toHaveBeenLastCalledWith(expect.objectContaining({ commandId: ruleId, categoryId }));
    response = await instance.inject({ method: "POST", url: `${root}/expenses`, payload: { ...write, commandId: expenseId.toUpperCase(), categoryId: categoryId.toUpperCase(), idempotencyKey: "replay" } }); expect(response.statusCode).toBe(200); expect(response.json()).toEqual({ ...base, item: expense, outcome: "replayed" }); response = await instance.inject({ method: "POST", url: `${root}/expenses`, payload: { ...write, commandId: ruleId.toUpperCase(), categoryId: categoryId.toUpperCase(), idempotencyKey: "replay", recurrence: { cadence: "monthly", startsOn: "2026-08-11" } } }); expect(response.statusCode).toBe(200); expect(response.json().outcome).toBe("replayed"); expect(await instance.inject({ method: "POST", url: `${root}/recurring-expenses`, payload: command })).toHaveProperty("statusCode", 404); await instance.close(); });

  it("does not let manage imply read or return resource payloads", async () => { const options = ports(), instance = await app(options, context({ permissions: ["pms.finance.manage"] })); let response = await instance.inject({ method: "POST", url: `${root}/expense-categories`, payload: { commandId: expenseId.toUpperCase(), idempotencyKey: "replay", name: "Operations", color: "#123456", sortOrder: 1 } }); expect(response.json()).toEqual({ contractVersion: "pms-financials.v1", propertyId, resourceId: categoryId, outcome: "replayed" }); expect(options.categories.create).toHaveBeenCalledWith(expect.objectContaining({ commandId: expenseId })); response = await instance.inject({ method: "POST", url: `${root}/expenses`, payload: write }); expect(response.json()).toEqual({ contractVersion: "pms-financials.v1", propertyId, resourceId: expenseId, outcome: "created" }); response = await instance.inject({ method: "POST", url: `${root}/expenses`, payload: { ...write, commandId: ruleId, recurrence: { cadence: "monthly", startsOn: "2026-08-11" } } }); expect(response.json()).toEqual({ contractVersion: "pms-financials.v1", propertyId, resourceId: ruleId, outcome: "created" }); expect(options.read.categories).not.toHaveBeenCalled(); expect(options.read.expense).not.toHaveBeenCalled(); expect(options.read.recurringRule).not.toHaveBeenCalled(); expect(await instance.inject({ method: "GET", url: `${root}/expense-categories` })).toHaveProperty("statusCode", 403); await instance.close(); });

  // prettier-ignore
  it("signs only an active receipt bound to a read-authorized property expense", async () => { let options = ports(), instance = await app(options), response = await instance.inject({ method: "GET", url: `${root}/expenses/${expenseId}/receipt` }); expect(response.statusCode).toBe(200); expect(response.json()).toEqual({ contractVersion: "pms-financials-receipt.v1", propertyId, expenseId, receipt: { mediaId: receiptId, disposition: { method: "GET", url: "https://signed.example/receipt?expires=300", expiresAt: "2026-08-11T10:05:00.000Z" } } }); expect(JSON.stringify(response.json())).not.toMatch(/storageKey|bucketName/); expect(options.receiptMedia!.signer.signPrivateDownload).toHaveBeenCalledOnce(); await instance.close(); options = ports(); instance = await app(options, context({ permissions: ["pms.finance.manage"] })); response = await instance.inject({ method: "GET", url: `${root}/expenses/${expenseId}/receipt` }); expect(response.statusCode).toBe(403); expect(options.receiptMedia!.read.receipt).not.toHaveBeenCalled(); expect(options.receiptMedia!.signer.signPrivateDownload).not.toHaveBeenCalled(); await instance.close(); options = ports(); options.receiptMedia!.read.receipt = vi.fn(async () => ({ purpose: "pms.messaging.attachment" })) as never; instance = await app(options); response = await instance.inject({ method: "GET", url: `${root}/expenses/${expenseId}/receipt` }); expect(response.statusCode).toBe(500); expect(options.receiptMedia!.signer.signPrivateDownload).not.toHaveBeenCalled(); await instance.close(); options = ports(); options.receiptMedia!.read.receipt = vi.fn(async () => null); instance = await app(options); response = await instance.inject({ method: "GET", url: `${root}/expenses/${expenseId}/receipt` }); expect(response.statusCode).toBe(404); expect(options.receiptMedia!.signer.signPrivateDownload).not.toHaveBeenCalled(); await instance.close(); });

  // prettier-ignore
  it("rejects wrong-purpose, wrong-resource, and staged receipt rows before signing", async () => { for (const override of [{ purpose: "pms.messaging.attachment" }, { resourceId: ruleId }, { lifecycleStatus: "staged" }]) { const options = ports(), media = await options.receiptMedia!.read.receipt(propertyId, expenseId); options.receiptMedia!.read.receipt = vi.fn(async () => ({ ...media!, ...override })) as never; const instance = await app(options), response = await instance.inject({ method: "GET", url: `${root}/expenses/${expenseId}/receipt` }); expect(response.statusCode).toBe(500); expect(options.receiptMedia!.signer.signPrivateDownload).not.toHaveBeenCalled(); await instance.close(); } });

  it("rejects authorization gaps before validation or ports", async () => { const valid = context(), denied: Array<[RequestContext | null, number]> = [[null, 401], [context({ permissions: [] }), 403], [context({ kind: "platform" }), 403], [context({ entitlements: [entitlement("module:financials")] }), 403], [context({ entitlements: [entitlement("property-management", "suspended"), entitlement("module:financials")] }), 403], [context({ entitlements: [entitlement("property-management"), entitlement("module:financials", "suspended")] }), 403], [context({ links: [] }), 403], [context({ links: [{ ...valid.linkedResources[0]!, relationship: "operator" }] }), 403]]; for (const [auth, status] of denied) { const options = ports(), instance = await app(options, auth), response = await instance.inject({ method: "GET", url: `${root}/expenses/not-a-uuid?secret=1` }); expect(response.statusCode).toBe(status); expect(options.read.expense).not.toHaveBeenCalled(); await instance.close(); } const options = ports(), instance = await app(options, context({ permissions: ["pms.finance.read"] })); expect(await instance.inject({ method: "POST", url: `${root}/expenses`, payload: { secret: true } })).toHaveProperty("statusCode", 403); expect(options.expenses.create).not.toHaveBeenCalled(); await instance.close(); });

  it("validates strict settlement and recurrence inputs before ports", async () => { const options = ports(), instance = await app(options); for (const payload of [{ ...write, paymentStatus: "paid" }, { ...write, paidOn: "2026-08-11" }, { ...write, paymentStatus: "unpaid", paidOn: "2026-08-11" }, { ...write, recurrence: { cadence: "monthly", startsOn: "2026-02-30" } }]) expect(await instance.inject({ method: "POST", url: `${root}/expenses`, payload })).toHaveProperty("statusCode", 400); expect(options.expenses.create).not.toHaveBeenCalled(); expect(options.recurring.create).not.toHaveBeenCalled(); const response = await instance.inject({ method: "PATCH", url: `${root}/recurring-expenses/${ruleId}`, payload: { ...command, categoryId, vendor: "Vendor", amount: { amount: "12", currency: "EUR" }, notes: null, paymentStatus: "paid", cadence: "weekly", nextDueOn: "2026-08-18", endsOn: null } }); expect(response.statusCode).toBe(200); expect(options.recurring.update).toHaveBeenCalledWith(expect.objectContaining({ endsOn: null, amount: write.amount })); await instance.close(); });

  it("maps typed command failures and missing reads without leaking port data", async () => { const cases = [["invalid_command", 400], ["not_found", 404], ["currency_mismatch", 422], ["evidence_mismatch", 422], ["write_unavailable", 422], ["revision_conflict", 409], ["idempotency_conflict", 409]] as const; for (const [code, status] of cases) { const options = ports(); options.expenses.create = vi.fn(async () => ({ ok: false, code })) as never; const instance = await app(options), response = await instance.inject({ method: "POST", url: `${root}/expenses`, payload: write }); expect(response.statusCode).toBe(status); expect(options.read.expense).not.toHaveBeenCalled(); await instance.close(); } const options = ports(); options.read.expense = vi.fn(async () => null) as never; const instance = await app(options); expect(await instance.inject({ method: "GET", url: `${root}/expenses/${expenseId}` })).toHaveProperty("statusCode", 404); await instance.close(); });

  it("fails closed on cross-property scope and tampered read or command envelopes", async () => { let options = ports(), instance = await app(options); let response = await instance.inject({ method: "GET", url: `/api/finance/properties/${otherProperty}/financials/expense-categories` }); expect(response.statusCode).toBe(403); expect(options.read.categories).not.toHaveBeenCalled(); await instance.close(); options = ports(); options.read.categories = vi.fn(async () => ({ ...base, propertyId: otherProperty, item: [category] })) as never; instance = await app(options); response = await instance.inject({ method: "GET", url: `${root}/expense-categories` }); expect(response.statusCode).toBe(500); await instance.close(); options = ports(); options.read.categories = vi.fn(async () => ({ ...base, generatedAt: "2026-02-30T00:00:00Z", item: [category] })) as never; instance = await app(options); response = await instance.inject({ method: "GET", url: `${root}/expense-categories` }); expect(response.statusCode).toBe(500); await instance.close(); options = ports(); options.categories.create = vi.fn(async () => ({ status: "created", category: { ...category, id: otherProperty } })) as never; instance = await app(options); response = await instance.inject({ method: "POST", url: `${root}/expense-categories`, payload: { commandId: categoryId, idempotencyKey: "key-1", name: "Operations", color: "#123456", sortOrder: 1 } }); expect(response.statusCode).toBe(500); await instance.close(); options = ports(); options.expenses.create = vi.fn(async () => ({ ok: true, outcome: "created", item: { ...expense, providerSecret: "no" } })) as never; instance = await app(options); response = await instance.inject({ method: "POST", url: `${root}/expenses`, payload: write }); expect(response.statusCode).toBe(500); expect(options.read.expense).not.toHaveBeenCalled(); await instance.close(); });
});

// prettier-ignore
const resource = { product: "pms" as const, resourceType: "pms_property" as const, resourceId: propertyId }, entitlement = (key: string, status: ProductEntitlement["status"] = "active"): ProductEntitlement => ({ product: "pms", key, status, resource }), context = (overrides: { permissions?: PermissionKey[]; entitlements?: ProductEntitlement[]; links?: LinkedResource[]; kind?: "hotel_group" | "platform" } = {}): RequestContext => ({ actor: { internalUserId: "12140000-0000-4000-8000-000000000010", status: "active" }, selectedOrganization: { organizationId: "12140000-0000-4000-8000-000000000011", kind: overrides.kind ?? "hotel_group", status: "active" }, membership: { roleKey: "hotel_owner", status: "active", propertyAccess: { mode: "assigned", roleKey: "hotel_owner", accessOrigin: "agency", assignedPropertyIds: [propertyId] }, permissions: overrides.permissions ?? ["pms.finance.read", "pms.finance.manage"] }, entitlements: overrides.entitlements ?? [entitlement("property-management"), entitlement("module:financials")], linkedResources: overrides.links ?? [{ ...resource, relationship: "owner", status: "active" }, { product: "hotel_catalog", resourceType: "property", resourceId: propertyId, relationship: "owner", status: "active" }], locale: "en", currency: "EUR", audit: { requestId: "request-1", receivedAt: now, source: "api" } } as unknown as RequestContext);
