import {
  assertHotelSetupColumnPrivileges,
  type HotelSetupColumnPrivileges,
  type HotelSetupPrivilegeQueryable,
} from "./hotelSetupReaderPrivileges.js";

/** Exact native logo protocol columns; no ordinary API grants. */
export const HOTEL_SETUP_LOGO_PRIVILEGES: HotelSetupColumnPrivileges = {
  "identity.organizations": {
    SELECT: ["id", "kind", "status"],
    UPDATE: ["id"],
  },
  "identity.organization_resource_links": {
    SELECT: [
      "organization_id",
      "product",
      "resource_type",
      "resource_id",
      "relationship",
      "status",
    ],
    UPDATE: ["organization_id"],
  },
  "hotel_catalog.properties": {
    SELECT: ["id", "profile_revision", "default_locale", "profile_status"],
    UPDATE: ["profile_revision", "completeness_reasons", "profile_status", "updated_at"],
  },
  "hotel_catalog.property_profiles": {
    SELECT: ["property_id", "locale", "short_description", "long_description"],
  },
  "hotel_catalog.property_media": {
    SELECT: [
      "id",
      "property_id",
      "media_type",
      "source_system",
      "public_approved",
      "platform_media_object_id",
      "rights_metadata",
      "alt_text",
      "sort_order",
    ],
    INSERT: [
      "property_id",
      "media_type",
      "url",
      "alt_text",
      "sort_order",
      "source_system",
      "public_approved",
      "rights_metadata",
      "platform_media_object_id",
      "updated_at",
    ],
  },
  "platform.media_upload_sessions": {
    SELECT: [
      "id",
      "upload_session_key",
      "requested_purpose",
      "requested_visibility",
      "actor_user_id",
      "owner_organization_id",
      "property_id",
      "resource_product",
      "resource_type",
      "resource_id",
      "expected_content_type",
      "expected_size_bytes",
      "expected_file_count",
      "staging_prefix",
      "expires_at",
      "session_status",
      "completed_media_object_id",
      "completion_metadata",
      "private_artifact_manifest",
      "created_at",
      "updated_at",
      "completed_at",
    ],
    INSERT: [
      "id",
      "upload_session_key",
      "requested_purpose",
      "requested_visibility",
      "actor_user_id",
      "owner_organization_id",
      "property_id",
      "resource_product",
      "resource_type",
      "resource_id",
      "expected_content_type",
      "expected_size_bytes",
      "expected_file_count",
      "staging_prefix",
      "expires_at",
      "session_status",
      "completion_metadata",
      "created_at",
      "updated_at",
    ],
    UPDATE: [
      "expires_at",
      "session_status",
      "completed_media_object_id",
      "completion_metadata",
      "private_artifact_manifest",
      "completed_at",
      "updated_at",
    ],
  },
  "platform.media_objects": {
    SELECT: [
      "id",
      "bucket",
      "storage_key",
      "storage_kind",
      "visibility",
      "purpose",
      "owner_organization_id",
      "property_id",
      "resource_product",
      "resource_type",
      "resource_id",
      "lifecycle_status",
      "content_type",
      "size_bytes",
      "checksum_sha256",
      "width_px",
      "height_px",
      "original_filename",
      "source_metadata",
      "public_approved",
      "retained_until",
      "created_by_user_id",
      "created_at",
      "updated_at",
    ],
    INSERT: [
      "id",
      "bucket",
      "storage_key",
      "storage_kind",
      "visibility",
      "purpose",
      "owner_organization_id",
      "property_id",
      "resource_product",
      "resource_type",
      "resource_id",
      "lifecycle_status",
      "content_type",
      "size_bytes",
      "checksum_sha256",
      "width_px",
      "height_px",
      "original_filename",
      "source_metadata",
      "public_approved",
      "retained_until",
      "created_by_user_id",
      "created_at",
      "updated_at",
    ],
    UPDATE: ["visibility", "storage_key", "lifecycle_status", "public_approved", "updated_at"],
  },
  "platform.media_variants": {
    SELECT: [
      "id",
      "media_object_id",
      "variant_name",
      "visibility",
      "storage_key",
      "content_type",
      "width_px",
      "height_px",
      "size_bytes",
      "checksum_sha256",
      "public_cdn_url",
      "created_at",
    ],
    INSERT: [
      "media_object_id",
      "variant_name",
      "visibility",
      "storage_key",
      "content_type",
      "width_px",
      "height_px",
      "size_bytes",
      "checksum_sha256",
      "public_cdn_url",
      "created_at",
    ],
    UPDATE: ["visibility", "storage_key", "public_cdn_url"],
  },
  "platform.idempotency_keys": {
    SELECT: [
      "id",
      "property_id",
      "tenant_scope",
      "organization_id",
      "operation_scope",
      "operation",
      "key_hash",
      "request_fingerprint_hash",
      "status",
      "response_status_code",
      "response_body_hash",
      "idempotency_metadata",
      "locked_until",
      "response_resource_product",
      "response_resource_type",
      "response_resource_id",
    ],
    INSERT: [
      "operation_scope",
      "operation",
      "key_hash",
      "request_fingerprint_hash",
      "tenant_scope",
      "property_id",
      "correlation_id",
      "expires_at",
      "idempotency_metadata",
    ],
    UPDATE: [
      "status",
      "response_status_code",
      "response_body_hash",
      "completed_at",
      "last_seen_at",
      "locked_until",
      "idempotency_metadata",
    ],
  },
  "platform.jobs": {
    SELECT: [
      "id",
      "job_key",
      "queue_name",
      "job_type",
      "priority",
      "status",
      "attempts_count",
      "max_attempts",
      "run_after",
      "locked_at",
      "locked_by",
      "finished_at",
      "tenant_scope",
      "organization_id",
      "property_id",
      "resource_product",
      "resource_type",
      "resource_id",
      "correlation_id",
      "idempotency_key_hash",
      "payload",
      "job_metadata",
      "created_at",
      "updated_at",
    ],
    INSERT: [
      "job_key",
      "queue_name",
      "job_type",
      "status",
      "max_attempts",
      "tenant_scope",
      "property_id",
      "resource_product",
      "resource_type",
      "resource_id",
      "correlation_id",
      "idempotency_key_hash",
      "payload",
      "job_metadata",
    ],
    UPDATE: [
      "status",
      "attempts_count",
      "run_after",
      "locked_at",
      "locked_by",
      "finished_at",
      "updated_at",
      "job_metadata",
    ],
  },
  "platform.job_attempts": {
    SELECT: [
      "id",
      "job_id",
      "attempt_number",
      "status",
      "worker_id",
      "started_at",
      "finished_at",
      "error_metadata",
    ],
    INSERT: [
      "job_id",
      "attempt_number",
      "status",
      "worker_id",
      "started_at",
      "finished_at",
      "error_type",
      "error_message",
      "error_metadata",
    ],
    UPDATE: [
      "status",
      "worker_id",
      "started_at",
      "finished_at",
      "duration_ms",
      "error_type",
      "error_message",
      "retry_after",
      "error_metadata",
    ],
  },
  "platform.dead_letter_events": {
    SELECT: ["source_kind", "job_id", "recovery_status"],
    INSERT: [
      "source_kind",
      "job_id",
      "job_attempt_id",
      "tenant_scope",
      "property_id",
      "resource_product",
      "resource_type",
      "resource_id",
      "correlation_id",
      "idempotency_key_hash",
      "reason_code",
      "failure_summary",
      "failure_payload",
    ],
  },
  "platform.product_audit_events": {
    SELECT: ["product", "audit_key"],
    INSERT: [
      "audit_key",
      "product",
      "action",
      "occurred_at",
      "tenant_scope",
      "organization_id",
      "property_id",
      "actor_type",
      "actor_user_id",
      "target_resource_product",
      "target_resource_type",
      "target_resource_id",
      "job_id",
      "idempotency_key_id",
      "correlation_id",
      "causation_id",
      "redacted_payload",
      "audit_metadata",
      "retention_class",
      "privacy_scope",
    ],
  },
};
export const HOTEL_SETUP_LOGO_RLS_HELPERS = [
  "platform.hotel_setup_logo_allowed(uuid,uuid,uuid)",
  "platform.hotel_setup_logo_bootstrap_proof_allowed(uuid,uuid,uuid)",
  "platform.hotel_setup_logo_row_allowed(uuid,uuid,uuid)",
  "platform.hotel_setup_logo_session_binding(uuid,uuid,uuid,uuid,jsonb)",
  "platform.hotel_setup_logo_login_guard()",
  "platform.hotel_setup_logo_context()",
  "platform.hotel_setup_logo_property(uuid)",
  "platform.hotel_setup_logo_organization(uuid)",
  "platform.hotel_setup_logo_media_read(uuid)",
  "platform.hotel_setup_logo_media_upload_binding(uuid)",
  "platform.hotel_setup_logo_job_read(uuid)",
  "platform.hotel_setup_logo_safe_variant(uuid,text,text,text,text,integer,integer,bigint,text,text)",
  "platform.hotel_setup_logo_session_valid(uuid,uuid,uuid,uuid,text,uuid,jsonb)",
  "platform.hotel_setup_logo_manifest_valid(jsonb,jsonb)",
  "platform.hotel_setup_logo_job_valid(uuid,jsonb)",
  "platform.hotel_setup_logo_public_key(uuid,text,text,text)",
  "platform.sync_hotel_setup_logo_read_models(uuid)",
  "platform.tenant_scope_key(text,uuid,uuid)",
  "platform.valid_tenant_scope(text,uuid,uuid)",
  "platform.valid_media_purpose_visibility(text,text)",
  "platform.hotel_setup_reader_audit_allowed(platform.product_audit_events)",
  "platform.channex_management_worker_source(text,text,uuid)",
  "platform.channex_management_worker_scope(text,text,uuid)",
  "platform.finance_expense_worker_scope(text,text,uuid)",
  "platform.finance_export_worker_scope(text,text,uuid)",
] as const;
const definers = [
  "platform.hotel_setup_logo_allowed(uuid,uuid,uuid)",
  "platform.hotel_setup_logo_bootstrap_proof_allowed(uuid,uuid,uuid)",
  "platform.hotel_setup_logo_context()",
  "platform.hotel_setup_logo_media_read(uuid)",
  "platform.hotel_setup_logo_media_upload_binding(uuid)",
  "platform.hotel_setup_logo_job_read(uuid)",
  "platform.hotel_setup_logo_session_valid(uuid,uuid,uuid,uuid,text,uuid,jsonb)",
  "platform.hotel_setup_logo_manifest_valid(jsonb,jsonb)",
  "platform.hotel_setup_logo_job_valid(uuid,jsonb)",
  "platform.hotel_setup_logo_public_key(uuid,text,text,text)",
  "platform.sync_hotel_setup_logo_read_models(uuid)",
] as const;

/** Inside BEGIN, before current actor/scope checks and any write or replay. */
export async function assertHotelSetupLogoPrivileges(client: HotelSetupPrivilegeQueryable) {
  await assertHotelSetupColumnPrivileges(client, HOTEL_SETUP_LOGO_PRIVILEGES, definers, [
    "hotel_catalog.property_media",
  ]);
  const result = await client.query<{ safe: boolean }>(
    `SELECT (
    (SELECT count(*) FROM pg_proc p WHERE p.oid=ANY($1::regprocedure[])
      AND has_function_privilege(current_user,p.oid,'EXECUTE')
      AND NOT has_function_privilege(current_user,p.oid,'EXECUTE WITH GRANT OPTION')
      AND p.proowner=(SELECT relowner FROM pg_class WHERE oid='platform.hotel_setup_property_scopes'::regclass)
      AND (p.proname NOT LIKE 'hotel_setup_logo_%' OR p.proconfig=ARRAY['search_path=pg_catalog']::text[]))=$3
    AND (SELECT md5(string_agg(pg_get_functiondef(p.oid),'' ORDER BY p.oid::regprocedure::text))
      FROM pg_proc p WHERE p.oid=ANY($1::regprocedure[] || ARRAY['platform.hotel_setup_logo_authority(uuid,uuid,uuid,boolean)'::regprocedure]))='2fb622fd71c5a7e0894a189fcc56ecd4'
    AND (SELECT md5(string_agg(c.oid::regclass::text||c.relrowsecurity::text||c.relforcerowsecurity::text||p.polname
      ||p.polpermissive::text||p.polcmd::text
      ||COALESCE((SELECT string_agg(CASE WHEN role=0 THEN 'PUBLIC' ELSE role::regrole::text END,',' ORDER BY role::regrole::text)
        FROM unnest(p.polroles) roles(role)),'')
      ||COALESCE(pg_get_expr(p.polqual,p.polrelid),'')||COALESCE(pg_get_expr(p.polwithcheck,p.polrelid),''),' ' ORDER BY c.oid::regclass::text,p.polname))
      FROM pg_class c JOIN pg_policy p ON p.polrelid=c.oid WHERE c.oid=ANY($2::regclass[]))='7b295d5a3753af419bbc2c44fc231cb9'
    AND (SELECT md5(string_agg(c.oid::regclass::text||pg_get_triggerdef(t.oid)||pg_get_functiondef(t.tgfoid)||t.tgenabled::text,'' ORDER BY c.oid::regclass::text,t.tgname))
      FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid WHERE NOT t.tgisinternal AND c.oid=ANY($2::regclass[]))='68b11515042c1756a1b45f82abd21f22'
    AND NOT EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=ANY($2::regclass[]) AND c.relowner<>(SELECT relowner FROM pg_class WHERE oid='platform.hotel_setup_property_scopes'::regclass))
    AND NOT has_function_privilege(current_user,'platform.hotel_setup_logo_authority(uuid,uuid,uuid,boolean)','EXECUTE')
    AND (SELECT p.prosecdef AND p.proconfig=ARRAY['search_path=pg_catalog']::text[]
      AND p.proowner=(SELECT relowner FROM pg_class WHERE oid='platform.hotel_setup_property_scopes'::regclass)
      FROM pg_proc p WHERE p.oid='platform.hotel_setup_logo_authority(uuid,uuid,uuid,boolean)'::regprocedure)
    AND NOT EXISTS(SELECT 1 FROM pg_trigger t JOIN pg_proc p ON p.oid=t.tgfoid
      WHERE NOT t.tgisinternal AND t.tgrelid=ANY($2::regclass[]) AND p.proowner<>(SELECT relowner FROM pg_class WHERE oid='platform.hotel_setup_property_scopes'::regclass))
    AND NOT EXISTS(SELECT 1 FROM pg_auth_members WHERE member=(SELECT oid FROM pg_roles WHERE rolname='vayada_next_hotel_setup_logo_scope'))
    AND NOT EXISTS(SELECT 1 FROM pg_proc p,LATERAL aclexplode(p.proacl) a
      WHERE p.pronamespace='pg_catalog'::regnamespace AND a.grantee IN
        ((SELECT oid FROM pg_roles WHERE rolname=session_user),(SELECT oid FROM pg_roles WHERE rolname='vayada_next_hotel_setup_logo_scope')))
    AND NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.pronamespace='pg_catalog'::regnamespace
      AND p.proname IN ('pg_read_file','pg_read_binary_file','pg_ls_dir','lo_import','lo_export')
      AND has_function_privilege(current_user,p.oid,'EXECUTE'))
    AND current_user=session_user
    AND current_setting('session_replication_role')='origin' AND NOT has_parameter_privilege(current_user,'session_replication_role','SET')
  ) AS safe`,
    [
      HOTEL_SETUP_LOGO_RLS_HELPERS,
      Object.keys(HOTEL_SETUP_LOGO_PRIVILEGES),
      HOTEL_SETUP_LOGO_RLS_HELPERS.length,
    ],
  );
  if (result.rows.length !== 1 || result.rows[0]?.safe !== true)
    throw new Error("Hotel setup logo native inventory mismatch");
}
