export const TIMEZONE_OPTIONS = [
  'UTC',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Rome',
  'Europe/Madrid',
  'Europe/Amsterdam',
  'Europe/Brussels',
  'Europe/Vienna',
  'Europe/Zurich',
  'Europe/Athens',
  'Europe/Istanbul',
  'Europe/Moscow',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'Asia/Dubai',
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Australia/Sydney',
]

export const CURRENCY_OPTIONS = [
  { code: 'EUR', label: 'EUR - Euro' },
  { code: 'USD', label: 'USD - US Dollar' },
  { code: 'GBP', label: 'GBP - British Pound' },
  { code: 'CHF', label: 'CHF - Swiss Franc' },
  { code: 'SEK', label: 'SEK - Swedish Krona' },
  { code: 'NOK', label: 'NOK - Norwegian Krone' },
  { code: 'DKK', label: 'DKK - Danish Krone' },
  { code: 'PLN', label: 'PLN - Polish Zloty' },
  { code: 'CZK', label: 'CZK - Czech Koruna' },
  { code: 'HUF', label: 'HUF - Hungarian Forint' },
  { code: 'RON', label: 'RON - Romanian Leu' },
  { code: 'BGN', label: 'BGN - Bulgarian Lev' },
  { code: 'HRK', label: 'HRK - Croatian Kuna' },
  { code: 'TRY', label: 'TRY - Turkish Lira' },
  { code: 'RUB', label: 'RUB - Russian Ruble' },
  { code: 'JPY', label: 'JPY - Japanese Yen' },
  { code: 'CNY', label: 'CNY - Chinese Yuan' },
  { code: 'AUD', label: 'AUD - Australian Dollar' },
  { code: 'CAD', label: 'CAD - Canadian Dollar' },
  { code: 'SGD', label: 'SGD - Singapore Dollar' },
  { code: 'AED', label: 'AED - UAE Dirham' },
  { code: 'THB', label: 'THB - Thai Baht' },
  { code: 'INR', label: 'INR - Indian Rupee' },
  { code: 'BRL', label: 'BRL - Brazilian Real' },
  { code: 'MXN', label: 'MXN - Mexican Peso' },
]
