export const STRIPE_COUNTRIES = [
  { c: "AE", n: "United Arab Emirates", f: "🇦🇪" },
  { c: "AR", n: "Argentina", f: "🇦🇷" },
  { c: "AT", n: "Austria", f: "🇦🇹" },
  { c: "AU", n: "Australia", f: "🇦🇺" },
  { c: "BE", n: "Belgium", f: "🇧🇪" },
  { c: "BG", n: "Bulgaria", f: "🇧🇬" },
  { c: "BO", n: "Bolivia", f: "🇧🇴" },
  { c: "BR", n: "Brazil", f: "🇧🇷" },
  { c: "CA", n: "Canada", f: "🇨🇦" },
  { c: "CH", n: "Switzerland", f: "🇨🇭" },
  { c: "CL", n: "Chile", f: "🇨🇱" },
  { c: "CO", n: "Colombia", f: "🇨🇴" },
  { c: "CR", n: "Costa Rica", f: "🇨🇷" },
  { c: "CY", n: "Cyprus", f: "🇨🇾" },
  { c: "CZ", n: "Czech Republic", f: "🇨🇿" },
  { c: "DE", n: "Germany", f: "🇩🇪" },
  { c: "DK", n: "Denmark", f: "🇩🇰" },
  { c: "DO", n: "Dominican Republic", f: "🇩🇴" },
  { c: "EE", n: "Estonia", f: "🇪🇪" },
  { c: "EG", n: "Egypt", f: "🇪🇬" },
  { c: "ES", n: "Spain", f: "🇪🇸" },
  { c: "FI", n: "Finland", f: "🇫🇮" },
  { c: "FR", n: "France", f: "🇫🇷" },
  { c: "GB", n: "United Kingdom", f: "🇬🇧" },
  { c: "GH", n: "Ghana", f: "🇬🇭" },
  { c: "GR", n: "Greece", f: "🇬🇷" },
  { c: "GT", n: "Guatemala", f: "🇬🇹" },
  { c: "HK", n: "Hong Kong", f: "🇭🇰" },
  { c: "HR", n: "Croatia", f: "🇭🇷" },
  { c: "HU", n: "Hungary", f: "🇭🇺" },
  { c: "ID", n: "Indonesia", f: "🇮🇩" },
  { c: "IE", n: "Ireland", f: "🇮🇪" },
  { c: "IL", n: "Israel", f: "🇮🇱" },
  { c: "IN", n: "India", f: "🇮🇳" },
  { c: "IS", n: "Iceland", f: "🇮🇸" },
  { c: "IT", n: "Italy", f: "🇮🇹" },
  { c: "JM", n: "Jamaica", f: "🇯🇲" },
  { c: "JP", n: "Japan", f: "🇯🇵" },
  { c: "KE", n: "Kenya", f: "🇰🇪" },
  { c: "KR", n: "South Korea", f: "🇰🇷" },
  { c: "LI", n: "Liechtenstein", f: "🇱🇮" },
  { c: "LT", n: "Lithuania", f: "🇱🇹" },
  { c: "LU", n: "Luxembourg", f: "🇱🇺" },
  { c: "LV", n: "Latvia", f: "🇱🇻" },
  { c: "MA", n: "Morocco", f: "🇲🇦" },
  { c: "MT", n: "Malta", f: "🇲🇹" },
  { c: "MX", n: "Mexico", f: "🇲🇽" },
  { c: "MY", n: "Malaysia", f: "🇲🇾" },
  { c: "NG", n: "Nigeria", f: "🇳🇬" },
  { c: "NL", n: "Netherlands", f: "🇳🇱" },
  { c: "NO", n: "Norway", f: "🇳🇴" },
  { c: "NZ", n: "New Zealand", f: "🇳🇿" },
  { c: "PA", n: "Panama", f: "🇵🇦" },
  { c: "PE", n: "Peru", f: "🇵🇪" },
  { c: "PH", n: "Philippines", f: "🇵🇭" },
  { c: "PL", n: "Poland", f: "🇵🇱" },
  { c: "PT", n: "Portugal", f: "🇵🇹" },
  { c: "PY", n: "Paraguay", f: "🇵🇾" },
  { c: "RO", n: "Romania", f: "🇷🇴" },
  { c: "RS", n: "Serbia", f: "🇷🇸" },
  { c: "SA", n: "Saudi Arabia", f: "🇸🇦" },
  { c: "SE", n: "Sweden", f: "🇸🇪" },
  { c: "SG", n: "Singapore", f: "🇸🇬" },
  { c: "SI", n: "Slovenia", f: "🇸🇮" },
  { c: "SK", n: "Slovakia", f: "🇸🇰" },
  { c: "TH", n: "Thailand", f: "🇹🇭" },
  { c: "TN", n: "Tunisia", f: "🇹🇳" },
  { c: "TR", n: "Turkey", f: "🇹🇷" },
  { c: "TT", n: "Trinidad & Tobago", f: "🇹🇹" },
  { c: "TW", n: "Taiwan", f: "🇹🇼" },
  { c: "US", n: "United States", f: "🇺🇸" },
  { c: "UY", n: "Uruguay", f: "🇺🇾" },
  { c: "VN", n: "Vietnam", f: "🇻🇳" },
  { c: "ZA", n: "South Africa", f: "🇿🇦" },
].sort((a, b) => a.n.localeCompare(b.n));
