export function getCurrencySymbol(currency: string): string {
  const symbols: Record<string, string> = {
    USD: "$",
    EUR: "€",
    GBP: "£",
    JPY: "¥",
    CNY: "¥",
    KRW: "₩",
    INR: "₹",
    THB: "฿",
    IDR: "IDR ",
    MYR: "RM",
    PHP: "₱",
    VND: "₫",
    SGD: "S$",
    AUD: "A$",
    NZD: "NZ$",
    CAD: "C$",
    CHF: "CHF",
    SEK: "kr",
    NOK: "kr",
    DKK: "kr",
    HKD: "HK$",
    TWD: "NT$",
    ZAR: "R",
    BRL: "R$",
    MXN: "MX$",
    AED: "AED",
    SAR: "SAR",
    TRY: "₺",
    PLN: "zł",
    CZK: "Kč",
    HUF: "Ft",
    RON: "lei",
    HRK: "kn",
    RUB: "₽",
    ILS: "₪",
    EGP: "E£",
    MAD: "MAD",
    KES: "KSh",
    NGN: "₦",
    GHS: "GH₵",
    COP: "COL$",
    PEN: "S/.",
    CLP: "CLP$",
    ARS: "ARS$",
  };
  return symbols[currency] || currency;
}
