-- Add property detail fields needed for Channex provisioning and OTA channel connections
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS property_type TEXT NOT NULL DEFAULT 'guest_house';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'Asia/Makassar';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS country TEXT NOT NULL DEFAULT '';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS state TEXT NOT NULL DEFAULT '';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS zip_code TEXT NOT NULL DEFAULT '';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS latitude NUMERIC(9,7);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7);
