ALTER TABLE room_types
    ADD COLUMN IF NOT EXISTS location_address TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS latitude NUMERIC(9,7),
    ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7);
